// Package consent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package consent

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// Defines values for XS2ABerlinConsentStatus.
const (
	Expired         XS2ABerlinConsentStatus = "expired"
	Received        XS2ABerlinConsentStatus = "received"
	Rejected        XS2ABerlinConsentStatus = "rejected"
	RevokedByPsu    XS2ABerlinConsentStatus = "revokedByPsu"
	TerminatedByTpp XS2ABerlinConsentStatus = "terminatedByTpp"
	Valid           XS2ABerlinConsentStatus = "valid"
)

// Valid indicates whether the value is a known member of the XS2ABerlinConsentStatus enum.
func (e XS2ABerlinConsentStatus) Valid() bool {
	switch e {
	case Expired:
		return true
	case Received:
		return true
	case Rejected:
		return true
	case RevokedByPsu:
		return true
	case TerminatedByTpp:
		return true
	case Valid:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticationType.
const (
	APPTOAPPANDROID AuthenticationType = "APP_TO_APP_ANDROID"
	APPTOAPPIOS     AuthenticationType = "APP_TO_APP_IOS"
	CHIPOTP         AuthenticationType = "CHIP_OTP"
	PHOTOOTP        AuthenticationType = "PHOTO_OTP"
	PUSHOTP         AuthenticationType = "PUSH_OTP"
	SCAREDIRECT     AuthenticationType = "SCAREDIRECT"
	SMSOTP          AuthenticationType = "SMS_OTP"
)

// Valid indicates whether the value is a known member of the AuthenticationType enum.
func (e AuthenticationType) Valid() bool {
	switch e {
	case APPTOAPPANDROID:
		return true
	case APPTOAPPIOS:
		return true
	case CHIPOTP:
		return true
	case PHOTOOTP:
		return true
	case PUSHOTP:
		return true
	case SCAREDIRECT:
		return true
	case SMSOTP:
		return true
	default:
		return false
	}
}

// XS2ABerlinConsent defines model for XS2A_Berlin_Consent.
type XS2ABerlinConsent struct {
	// Access All attributes are optional but at minimum one of these should exist.
	Access XS2ABerlinConsentAccountAccess `json:"access"`

	// ConsentStatus Authentication status of the consent.
	ConsentStatus *XS2ABerlinConsentStatus `json:"consentStatus,omitempty"`

	// FrequencyPerDay This field indicates the requested maximum frequency for an access per day. For a one-off access, this attribute is set to "1".
	FrequencyPerDay float32 `json:"frequencyPerDay"`

	// LastActionDate This date is containing the date of the last action on the consent object either through the XS2A interface or the PSU/ASPSP interface having an impact on the status.
	LastActionDate *openapi_types.Date `json:"lastActionDate,omitempty"`

	// RecurringIndicator true - if the consent is for recurring access to the account data. false - if the consent is for one access to the account data
	RecurringIndicator bool `json:"recurringIndicator"`

	// ValidUntil Datetime the transaction was created.
	ValidUntil openapi_types.Date `json:"validUntil"`
}

// XS2ABerlinConsentAccountAccess All attributes are optional but at minimum one of these should exist.
type XS2ABerlinConsentAccountAccess struct {
	Accounts              *[]XS2ABerlinConsentResources `json:"accounts,omitempty"`
	AdditionalInformation *struct {
		OwnerName *OwnerName `json:"ownerName,omitempty"`
	} `json:"additionalInformation,omitempty"`
	Balances     *[]XS2ABerlinConsentResources `json:"balances,omitempty"`
	Transactions *[]XS2ABerlinConsentResources `json:"transactions,omitempty"`
}

// XS2ABerlinConsentResources defines model for XS2A_Berlin_Consent_Resources.
type XS2ABerlinConsentResources struct {
	// Currency Currency of an account.
	Currency *string `json:"currency,omitempty"`

	// Iban IBAN of an account.
	Iban *string `json:"iban,omitempty"`
}

// XS2ABerlinConsentStatus Authentication status of the consent.
type XS2ABerlinConsentStatus string

// XS2ABerlinCreateConsentRequest defines model for XS2A_Berlin_Create_Consent_Request.
type XS2ABerlinCreateConsentRequest struct {
	// Access All attributes are optional but at minimum one of these should exist.
	Access XS2ABerlinConsentAccountAccess `json:"access"`

	// CombinedServiceIndicator true - indicates that a payment initiation service will be addressed in the same "session" - NOT IMPLEMENTED AT THE MOMENT
	CombinedServiceIndicator bool `json:"combinedServiceIndicator"`

	// FrequencyPerDay This field indicates the requested maximum frequency for an access per day. For a one-off access, this attribute is set to "1".
	FrequencyPerDay int `json:"frequencyPerDay"`

	// RecurringIndicator true - if the consent is for recurring access to the account data. false - if the consent is for one access to the account data
	RecurringIndicator bool `json:"recurringIndicator"`

	// ValidUntil Datetime the transaction was created.
	ValidUntil openapi_types.Date `json:"validUntil"`
}

// XS2ABerlinCreateConsentResponse defines model for XS2A_Berlin_Create_Consent_Response.
type XS2ABerlinCreateConsentResponse struct {
	UnderscoreLinks XS2ABerlinLinks `json:"_links"`

	// ConsentId Identification of the consent resource as it is used in the API structure. Shall be contained, if a consent resource was generated.
	ConsentId *string `json:"consentId,omitempty"`

	// ConsentStatus Authentication status of the consent.
	ConsentStatus XS2ABerlinConsentStatus `json:"consentStatus"`
	ScaMethods    *[]XS2AScaMethods       `json:"scaMethods,omitempty"`
}

// XS2ABerlinError defines model for XS2A_Berlin_Error.
type XS2ABerlinError struct {
	// ErrorCode Optional error code for reporting purposes.
	ErrorCode *string `json:"errorCode,omitempty"`

	// ErrorDescription The description of the error.
	ErrorDescription *string `json:"errorDescription,omitempty"`
}

// XS2ABerlinGetConsentStatusResponse defines model for XS2A_Berlin_Get_Consent_Status_Response.
type XS2ABerlinGetConsentStatusResponse struct {
	// ConsentStatus Authentication status of the consent.
	ConsentStatus XS2ABerlinConsentStatus `json:"consentStatus"`
}

// XS2ABerlinHref defines model for XS2A_Berlin_Href.
type XS2ABerlinHref struct {
	Href string `json:"href"`
}

// XS2ABerlinLinks defines model for XS2A_Berlin_Links.
type XS2ABerlinLinks struct {
	ScaRedirect XS2ABerlinHref `json:"scaRedirect"`
	Status      XS2ABerlinHref `json:"status"`
}

// XS2AScaMethods This data element might be contained, if SCA is required and if the PSU has a choice between different
// authentication methods.
//
// Depending on the risk management of the ASPSP this choice might be offered before or after the PSU
// has been identified with the first relevant factor, or if an access token is transported.
//
// If this data element is contained, then there is also an hyperlink of type 'startAuthorisationWithAuthenticationMethodSelection'
// contained in the response body.
//
// These methods shall be presented towards the PSU for selection by the TPP.
type XS2AScaMethods = []AuthenticationObject

// AuthenticationObject Authentication Object
type AuthenticationObject struct {
	// AuthenticationMethodId An identification provided by the ASPSP for the later identification of the authentication method selection.
	AuthenticationMethodId string             `json:"authenticationMethodId"`
	AuthenticationType     AuthenticationType `json:"authenticationType"`

	// AuthenticationVersion Depending on the "authenticationType".
	// This version can be used by differentiating authentication tools used within performing OTP generation in the same authentication type.
	// This version can be referred to in the ASPSP?s documentation.
	AuthenticationVersion *string `json:"authenticationVersion,omitempty"`

	// Explanation Detailed information about the SCA method for the PSU.
	Explanation *string `json:"explanation,omitempty"`

	// Name This is the name of the authentication method defined by the PSU in the Online Banking frontend of the ASPSP.
	// Alternatively this could be a description provided by the ASPSP like "SMS OTP on phone +49160 xxxxx 28".
	// This name shall be used by the TPP when presenting a list of authentication methods to the PSU, if available.
	Name *string `json:"name,omitempty"`
}

// AuthenticationType defines model for authenticationType.
type AuthenticationType string

// OwnerName defines model for ownerName.
type OwnerName = []XS2ABerlinConsentResources

// Digest defines model for digest.
type Digest = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// NewConsentParams defines parameters for NewConsent.
type NewConsentParams struct {
	// ClientId Client ID
	ClientId string `json:"client_id"`

	// XRequestID Request ID
	XRequestID string `json:"X-Request-ID"`

	// PSUID Client ID of the PSU in the ASPSP client interface. It is mandated by the Raiffeisen Bank to be required field if the PSU-Corporate-ID is not provided. It might be contained even if an OAuth2 based authentication was performed in a pre-step In this case the ASPSP might check whether PSU-ID and token match, according to ASPSP documentation.
	PSUID *string `json:"PSU-ID,omitempty"`

	// PSUIDType Type of the PSU-ID, needed in scenarios where PSUs have several PSU-IDs as access possibility.
	PSUIDType *string `json:"PSU-ID-Type,omitempty"`

	// PSUCorporateID It is mandated by the Raiffeisen Bank to be required field if the PSU-ID is not provided.
	PSUCorporateID *string `json:"PSU-Corporate-ID,omitempty"`

	// PSUCorporateIDType Might be mandated in the ASPSP's documentation. Only used in a corporate context.
	PSUCorporateIDType *string `json:"PSU-Corporate-ID-Type,omitempty"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// TPPRedirectPreferred If it equals "true", the TPP prefers a redirect over an embedded SCA approach.
	// If it equals "false", the TPP prefers not to be redirected for SCA. The ASPSP will then choose between the Embedded or the Decoupled
	// SCA approach, depending on the choice of the SCA procedure by the TPP/PSU.
	// If the parameter is not used, the ASPSP will choose the SCA approach to be applied depending on the SCA method chosen by the
	// TPP/PSU.
	TPPRedirectPreferred *bool `json:"TPP-Redirect-Preferred,omitempty"`

	// TPPRedirectURI URI of the URI of the TPP, where the transaction
	//   flow shall be redirected to after a
	//   Redirect. Mandated for the Redirect SCA
	//   Approach, specifically when TPP-Redirect-
	//   Preferred equals "true". See Section 4.10 for
	//   further requirements on this header.
	//   It is recommended to always use this header
	//   field.
	TPPRedirectURI *string `json:"TPP-Redirect-URI,omitempty"`

	// TPPNokRedirectURI If this URI is contained, the TPP is asking to redirect the transaction flow to this address instead of the TPP-Redirect-URI in case
	// of a negative result of the redirect SCA method. This might be ignored by the ASPSP.
	TPPNokRedirectURI *string `json:"TPP-Nok-Redirect-URI,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *string `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *string `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *string `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *string `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *string `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *string `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *string `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *string `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *openapi_types.UUID `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *string `json:"PSU-Geo-Location,omitempty"`
}

// DeleteConsentParams defines parameters for DeleteConsent.
type DeleteConsentParams struct {
	// ClientId Client ID
	ClientId string `json:"client_id"`

	// XRequestID Request ID
	XRequestID string `json:"X-Request-ID"`

	// Authorization OAuth2 based SCA was performed in the corresponding consent transaction or if OAuth2 has been used in a pre-step.
	Authorization string `json:"Authorization"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`
}

// GetConsentParams defines parameters for GetConsent.
type GetConsentParams struct {
	// ClientId Client ID
	ClientId string `json:"client_id"`

	// XRequestID Request ID
	XRequestID string `json:"X-Request-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`
}

// GetConsentStatusParams defines parameters for GetConsentStatus.
type GetConsentStatusParams struct {
	// XRequestID Request ID
	XRequestID string `json:"X-Request-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`
}

// NewConsentJSONRequestBody defines body for NewConsent for application/json ContentType.
type NewConsentJSONRequestBody = XS2ABerlinCreateConsentRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// NewConsentWithBody request with any body
	NewConsentWithBody(ctx context.Context, params *NewConsentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NewConsent(ctx context.Context, params *NewConsentParams, body NewConsentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteConsent request
	DeleteConsent(ctx context.Context, consentId string, params *DeleteConsentParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConsent request
	GetConsent(ctx context.Context, consentId string, params *GetConsentParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConsentStatus request
	GetConsentStatus(ctx context.Context, consentId string, params *GetConsentStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) NewConsentWithBody(ctx context.Context, params *NewConsentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewConsentRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewConsent(ctx context.Context, params *NewConsentParams, body NewConsentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewConsentRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteConsent(ctx context.Context, consentId string, params *DeleteConsentParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteConsentRequest(c.Server, consentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConsent(ctx context.Context, consentId string, params *GetConsentParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConsentRequest(c.Server, consentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConsentStatus(ctx context.Context, consentId string, params *GetConsentStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConsentStatusRequest(c.Server, consentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewNewConsentRequest calls the generic NewConsent builder with application/json body
func NewNewConsentRequest(server string, params *NewConsentParams, body NewConsentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNewConsentRequestWithBody(server, params, "application/json", bodyReader)
}

// NewNewConsentRequestWithBody generates requests for NewConsent with any type of body
func NewNewConsentRequestWithBody(server string, params *NewConsentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("client_id", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "UUID"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam1)

		if params.PSUID != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID", *params.PSUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID", headerParam2)
		}

		if params.PSUIDType != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID-Type", *params.PSUIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID-Type", headerParam3)
		}

		if params.PSUCorporateID != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID", *params.PSUCorporateID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID", headerParam4)
		}

		if params.PSUCorporateIDType != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID-Type", *params.PSUCorporateIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID-Type", headerParam5)
		}

		if params.Digest != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam6)
		}

		if params.Signature != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam7)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam8)
		}

		if params.TPPRedirectPreferred != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-Preferred", *params.TPPRedirectPreferred, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "boolean", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-Preferred", headerParam9)
		}

		if params.TPPRedirectURI != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-URI", *params.TPPRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-URI", headerParam10)
		}

		if params.TPPNokRedirectURI != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "TPP-Nok-Redirect-URI", *params.TPPNokRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Nok-Redirect-URI", headerParam11)
		}

		if params.PSUIPAddress != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam12)
		}

		if params.PSUIPPort != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam13)
		}

		if params.PSUAccept != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam14)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam15 string

			headerParam15, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam15)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam16 string

			headerParam16, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam16)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam17 string

			headerParam17, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam17)
		}

		if params.PSUUserAgent != nil {
			var headerParam18 string

			headerParam18, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam18)
		}

		if params.PSUHttpMethod != nil {
			var headerParam19 string

			headerParam19, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam19)
		}

		if params.PSUDeviceID != nil {
			var headerParam20 string

			headerParam20, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam20)
		}

		if params.PSUGeoLocation != nil {
			var headerParam21 string

			headerParam21, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam21)
		}

	}

	return req, nil
}

// NewDeleteConsentRequest generates requests for DeleteConsent
func NewDeleteConsentRequest(server string, consentId string, params *DeleteConsentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "UUID"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("client_id", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "UUID"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam2)

		if params.Digest != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam3)
		}

		if params.Signature != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam4)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam5)
		}

	}

	return req, nil
}

// NewGetConsentRequest generates requests for GetConsent
func NewGetConsentRequest(server string, consentId string, params *GetConsentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "UUID"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("client_id", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "UUID"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

	}

	return req, nil
}

// NewGetConsentStatusRequest generates requests for GetConsentStatus
func NewGetConsentStatusRequest(server string, consentId string, params *GetConsentStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "UUID"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "UUID"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		if params.Digest != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam1)
		}

		if params.Signature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam2)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam3)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// NewConsentWithBodyWithResponse request with any body
	NewConsentWithBodyWithResponse(ctx context.Context, params *NewConsentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewConsentResponse, error)

	NewConsentWithResponse(ctx context.Context, params *NewConsentParams, body NewConsentJSONRequestBody, reqEditors ...RequestEditorFn) (*NewConsentResponse, error)

	// DeleteConsentWithResponse request
	DeleteConsentWithResponse(ctx context.Context, consentId string, params *DeleteConsentParams, reqEditors ...RequestEditorFn) (*DeleteConsentResponse, error)

	// GetConsentWithResponse request
	GetConsentWithResponse(ctx context.Context, consentId string, params *GetConsentParams, reqEditors ...RequestEditorFn) (*GetConsentResponse, error)

	// GetConsentStatusWithResponse request
	GetConsentStatusWithResponse(ctx context.Context, consentId string, params *GetConsentStatusParams, reqEditors ...RequestEditorFn) (*GetConsentStatusResponse, error)
}

type NewConsentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinCreateConsentResponse
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r NewConsentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NewConsentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r NewConsentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteConsentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r DeleteConsentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteConsentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteConsentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConsentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinConsent
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetConsentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConsentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConsentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConsentStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinGetConsentStatusResponse
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetConsentStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConsentStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConsentStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// NewConsentWithBodyWithResponse request with arbitrary body returning *NewConsentResponse
func (c *ClientWithResponses) NewConsentWithBodyWithResponse(ctx context.Context, params *NewConsentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewConsentResponse, error) {
	rsp, err := c.NewConsentWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewConsentResponse(rsp)
}

func (c *ClientWithResponses) NewConsentWithResponse(ctx context.Context, params *NewConsentParams, body NewConsentJSONRequestBody, reqEditors ...RequestEditorFn) (*NewConsentResponse, error) {
	rsp, err := c.NewConsent(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewConsentResponse(rsp)
}

// DeleteConsentWithResponse request returning *DeleteConsentResponse
func (c *ClientWithResponses) DeleteConsentWithResponse(ctx context.Context, consentId string, params *DeleteConsentParams, reqEditors ...RequestEditorFn) (*DeleteConsentResponse, error) {
	rsp, err := c.DeleteConsent(ctx, consentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteConsentResponse(rsp)
}

// GetConsentWithResponse request returning *GetConsentResponse
func (c *ClientWithResponses) GetConsentWithResponse(ctx context.Context, consentId string, params *GetConsentParams, reqEditors ...RequestEditorFn) (*GetConsentResponse, error) {
	rsp, err := c.GetConsent(ctx, consentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConsentResponse(rsp)
}

// GetConsentStatusWithResponse request returning *GetConsentStatusResponse
func (c *ClientWithResponses) GetConsentStatusWithResponse(ctx context.Context, consentId string, params *GetConsentStatusParams, reqEditors ...RequestEditorFn) (*GetConsentStatusResponse, error) {
	rsp, err := c.GetConsentStatus(ctx, consentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConsentStatusResponse(rsp)
}

// ParseNewConsentResponse parses an HTTP response from a NewConsentWithResponse call
func ParseNewConsentResponse(rsp *http.Response) (*NewConsentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NewConsentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinCreateConsentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteConsentResponse parses an HTTP response from a DeleteConsentWithResponse call
func ParseDeleteConsentResponse(rsp *http.Response) (*DeleteConsentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteConsentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetConsentResponse parses an HTTP response from a GetConsentWithResponse call
func ParseGetConsentResponse(rsp *http.Response) (*GetConsentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConsentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinConsent
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetConsentStatusResponse parses an HTTP response from a GetConsentStatusWithResponse call
func ParseGetConsentStatusResponse(rsp *http.Response) (*GetConsentStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConsentStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinGetConsentStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
