// Package caf provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package caf

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	OAuth2Scopes         oAuth2ContextKey         = "OAuth2.Scopes"
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// Defines values for XS2ATppMessageCategory.
const (
	ERROR   XS2ATppMessageCategory = "ERROR"
	WARNING XS2ATppMessageCategory = "WARNING"
)

// Valid indicates whether the value is a known member of the XS2ATppMessageCategory enum.
func (e XS2ATppMessageCategory) Valid() bool {
	switch e {
	case ERROR:
		return true
	case WARNING:
		return true
	default:
		return false
	}
}

// XS2ABerlinError defines model for XS2A_Berlin_Error.
type XS2ABerlinError struct {
	TppMessages *[]XS2ATppMessage `json:"tppMessages,omitempty"`
}

// XS2ABerlinFundConfirmationAccount defines model for XS2A_Berlin_Fund_Confirmation_Account.
type XS2ABerlinFundConfirmationAccount struct {
	// Iban PSU account IBAN
	Iban *string `json:"iban,omitempty"`
}

// XS2ABerlinFundConfirmationInstructedAmount defines model for XS2A_Berlin_Fund_Confirmation_InstructedAmount.
type XS2ABerlinFundConfirmationInstructedAmount struct {
	// Amount Amount to be checked.
	Amount *string `json:"amount,omitempty"`

	// Currency Amount currency.
	Currency *string `json:"currency,omitempty"`
}

// XS2ABerlinFundConfirmationRequest defines model for XS2A_Berlin_Fund_Confirmation_Request.
type XS2ABerlinFundConfirmationRequest struct {
	Account XS2ABerlinFundConfirmationAccount `json:"account"`

	// CardNumber Card Number of the card issued by the PIISP. Shouldbe delivered if available.
	CardNumber       *string                                    `json:"cardNumber,omitempty"`
	InstructedAmount XS2ABerlinFundConfirmationInstructedAmount `json:"instructedAmount"`

	// Payee The merchant where the card is accepted as an information to the PSU.
	Payee *string `json:"payee,omitempty"`
}

// XS2ABerlinFundConfirmationResponse defines model for XS2A_Berlin_Fund_Confirmation_Response.
type XS2ABerlinFundConfirmationResponse struct {
	// FundsAvailable Equals true if sufficient funds are available at the time of the request, false otherwise.
	FundsAvailable *bool `json:"fundsAvailable,omitempty"`
}

// XS2ATppMessage defines model for XS2A_Tpp_Message.
type XS2ATppMessage struct {
	// Category State ERROR or WARNING.
	Category *XS2ATppMessageCategory `json:"category,omitempty"`

	// Code The code of the error.
	Code *string `json:"code,omitempty"`

	// Text The description of the error.
	Text *string `json:"text,omitempty"`
}

// XS2ATppMessageCategory State ERROR or WARNING.
type XS2ATppMessageCategory string

// ConsentID defines model for Consent-ID.
type ConsentID = string

// XRequestID defines model for X-Request-ID.
type XRequestID = string

// Digest defines model for digest.
type Digest = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// oAuth2ContextKey is the context key for OAuth2 security scheme
type oAuth2ContextKey string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// PostConfirmationOfFundsParams defines parameters for PostConfirmationOfFunds.
type PostConfirmationOfFundsParams struct {
	// XRequestID Request ID
	XRequestID XRequestID `json:"X-Request-ID"`
	ConsentID  ConsentID  `json:"Consent-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`
}

// PostConfirmationOfFundsJSONRequestBody defines body for PostConfirmationOfFunds for application/json ContentType.
type PostConfirmationOfFundsJSONRequestBody = XS2ABerlinFundConfirmationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostConfirmationOfFundsWithBody request with any body
	PostConfirmationOfFundsWithBody(ctx context.Context, params *PostConfirmationOfFundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostConfirmationOfFunds(ctx context.Context, params *PostConfirmationOfFundsParams, body PostConfirmationOfFundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostConfirmationOfFundsWithBody(ctx context.Context, params *PostConfirmationOfFundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostConfirmationOfFundsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostConfirmationOfFunds(ctx context.Context, params *PostConfirmationOfFundsParams, body PostConfirmationOfFundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostConfirmationOfFundsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostConfirmationOfFundsRequest calls the generic PostConfirmationOfFunds builder with application/json body
func NewPostConfirmationOfFundsRequest(server string, params *PostConfirmationOfFundsParams, body PostConfirmationOfFundsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostConfirmationOfFundsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostConfirmationOfFundsRequestWithBody generates requests for PostConfirmationOfFunds with any type of body
func NewPostConfirmationOfFundsRequestWithBody(server string, params *PostConfirmationOfFundsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/funds-confirmations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Consent-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostConfirmationOfFundsWithBodyWithResponse request with any body
	PostConfirmationOfFundsWithBodyWithResponse(ctx context.Context, params *PostConfirmationOfFundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostConfirmationOfFundsResponse, error)

	PostConfirmationOfFundsWithResponse(ctx context.Context, params *PostConfirmationOfFundsParams, body PostConfirmationOfFundsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostConfirmationOfFundsResponse, error)
}

type PostConfirmationOfFundsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinFundConfirmationResponse
	JSON400      *XS2ABerlinError
	JSON401      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r PostConfirmationOfFundsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostConfirmationOfFundsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostConfirmationOfFundsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostConfirmationOfFundsWithBodyWithResponse request with arbitrary body returning *PostConfirmationOfFundsResponse
func (c *ClientWithResponses) PostConfirmationOfFundsWithBodyWithResponse(ctx context.Context, params *PostConfirmationOfFundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostConfirmationOfFundsResponse, error) {
	rsp, err := c.PostConfirmationOfFundsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostConfirmationOfFundsResponse(rsp)
}

func (c *ClientWithResponses) PostConfirmationOfFundsWithResponse(ctx context.Context, params *PostConfirmationOfFundsParams, body PostConfirmationOfFundsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostConfirmationOfFundsResponse, error) {
	rsp, err := c.PostConfirmationOfFunds(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostConfirmationOfFundsResponse(rsp)
}

// ParsePostConfirmationOfFundsResponse parses an HTTP response from a PostConfirmationOfFundsWithResponse call
func ParsePostConfirmationOfFundsResponse(rsp *http.Response) (*PostConfirmationOfFundsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostConfirmationOfFundsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinFundConfirmationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
