// Package oauthcisp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oauthcisp

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AccessTokenResponseTokenType.
const (
	Bearer AccessTokenResponseTokenType = "bearer"
)

// Valid indicates whether the value is a known member of the AccessTokenResponseTokenType enum.
func (e AccessTokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for TokenBodyGrantType.
const (
	AuthorizationCode TokenBodyGrantType = "authorization_code"
	RefreshToken      TokenBodyGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the TokenBodyGrantType enum.
func (e TokenBodyGrantType) Valid() bool {
	switch e {
	case AuthorizationCode:
		return true
	case RefreshToken:
		return true
	default:
		return false
	}
}

// AccessTokenResponse defines model for access_token_response.
type AccessTokenResponse struct {
	AccessToken  string                       `json:"access_token"`
	ExpiresIn    int                          `json:"expires_in"`
	RefreshToken *string                      `json:"refresh_token,omitempty"`
	TokenType    AccessTokenResponseTokenType `json:"token_type"`
}

// AccessTokenResponseTokenType defines model for AccessTokenResponse.TokenType.
type AccessTokenResponseTokenType string

// TokenBody defines model for tokenBody.
type TokenBody struct {
	// ClientId Application client ID, can be provided in formData or using HTTP Basic Authentication
	ClientId string `json:"client_id"`

	// ClientSecret Application secret, must be provided in formData or using HTTP Basic Authentication
	ClientSecret string `json:"client_secret"`

	// Code Authorization code provided by the /oauth2/authorize endpoint
	Code string `json:"code"`

	// GrantType Type of grant
	GrantType TokenBodyGrantType `json:"grant_type"`

	// RedirectUri required only if the redirect_uri parameter was included in the authorization request /oauth2/authorize; their values MUST be identical.
	RedirectUri *string `json:"redirect_uri,omitempty"`
}

// TokenBodyGrantType Type of grant
type TokenBodyGrantType string

// CispOauth2TokenFormdataRequestBody defines body for CispOauth2Token for application/x-www-form-urlencoded ContentType.
type CispOauth2TokenFormdataRequestBody = TokenBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CispOauth2TokenWithBody request with any body
	CispOauth2TokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CispOauth2TokenWithFormdataBody(ctx context.Context, body CispOauth2TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CispOauth2TokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCispOauth2TokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CispOauth2TokenWithFormdataBody(ctx context.Context, body CispOauth2TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCispOauth2TokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCispOauth2TokenRequestWithFormdataBody calls the generic CispOauth2Token builder with application/x-www-form-urlencoded body
func NewCispOauth2TokenRequestWithFormdataBody(server string, body CispOauth2TokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewCispOauth2TokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewCispOauth2TokenRequestWithBody generates requests for CispOauth2Token with any type of body
func NewCispOauth2TokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cisp/oauth2/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CispOauth2TokenWithBodyWithResponse request with any body
	CispOauth2TokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CispOauth2TokenResponse, error)

	CispOauth2TokenWithFormdataBodyWithResponse(ctx context.Context, body CispOauth2TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*CispOauth2TokenResponse, error)
}

type CispOauth2TokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccessTokenResponse
}

// Status returns HTTPResponse.Status
func (r CispOauth2TokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CispOauth2TokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CispOauth2TokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CispOauth2TokenWithBodyWithResponse request with arbitrary body returning *CispOauth2TokenResponse
func (c *ClientWithResponses) CispOauth2TokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CispOauth2TokenResponse, error) {
	rsp, err := c.CispOauth2TokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCispOauth2TokenResponse(rsp)
}

func (c *ClientWithResponses) CispOauth2TokenWithFormdataBodyWithResponse(ctx context.Context, body CispOauth2TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*CispOauth2TokenResponse, error) {
	rsp, err := c.CispOauth2TokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCispOauth2TokenResponse(rsp)
}

// ParseCispOauth2TokenResponse parses an HTTP response from a CispOauth2TokenWithResponse call
func ParseCispOauth2TokenResponse(rsp *http.Response) (*CispOauth2TokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CispOauth2TokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccessTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
