// Package oauthbridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oauthbridge

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ResponseType.
const (
	ResponseTypeCode  ResponseType = "code"
	ResponseTypeToken ResponseType = "token"
)

// Valid indicates whether the value is a known member of the ResponseType enum.
func (e ResponseType) Valid() bool {
	switch e {
	case ResponseTypeCode:
		return true
	case ResponseTypeToken:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	ScopeAISP Scope = "AISP"
	ScopeCISP Scope = "CISP"
	ScopePISP Scope = "PISP"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case ScopeAISP:
		return true
	case ScopeCISP:
		return true
	case ScopePISP:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticationParamsResponseType.
const (
	AuthenticationParamsResponseTypeCode  AuthenticationParamsResponseType = "code"
	AuthenticationParamsResponseTypeToken AuthenticationParamsResponseType = "token"
)

// Valid indicates whether the value is a known member of the AuthenticationParamsResponseType enum.
func (e AuthenticationParamsResponseType) Valid() bool {
	switch e {
	case AuthenticationParamsResponseTypeCode:
		return true
	case AuthenticationParamsResponseTypeToken:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticationParamsScope.
const (
	AuthenticationParamsScopeAISP AuthenticationParamsScope = "AISP"
	AuthenticationParamsScopeCISP AuthenticationParamsScope = "CISP"
	AuthenticationParamsScopePISP AuthenticationParamsScope = "PISP"
)

// Valid indicates whether the value is a known member of the AuthenticationParamsScope enum.
func (e AuthenticationParamsScope) Valid() bool {
	switch e {
	case AuthenticationParamsScopeAISP:
		return true
	case AuthenticationParamsScopeCISP:
		return true
	case AuthenticationParamsScopePISP:
		return true
	default:
		return false
	}
}

// Defines values for RedirectParamsScope.
const (
	AISP RedirectParamsScope = "AISP"
	CISP RedirectParamsScope = "CISP"
	PISP RedirectParamsScope = "PISP"
)

// Valid indicates whether the value is a known member of the RedirectParamsScope enum.
func (e RedirectParamsScope) Valid() bool {
	switch e {
	case AISP:
		return true
	case CISP:
		return true
	case PISP:
		return true
	default:
		return false
	}
}

// XS2ABerlinError defines model for XS2A_Berlin_Error.
type XS2ABerlinError struct {
	// ErrorCode Optional error code for reporting purposes.
	ErrorCode *string `json:"errorCode,omitempty"`

	// ErrorDescription The description of the error.
	ErrorDescription *string `json:"errorDescription,omitempty"`
}

// ClientId defines model for clientId.
type ClientId = string

// Confirmation defines model for confirmation.
type Confirmation = string

// ConsentId defines model for consentId.
type ConsentId = string

// Error defines model for error.
type Error = string

// ErrorDescription defines model for error_description.
type ErrorDescription = string

// RedirectUri defines model for redirect_uri.
type RedirectUri = string

// ResponseType defines model for response_type.
type ResponseType string

// Rstate defines model for rstate.
type Rstate = string

// Scope defines model for scope.
type Scope string

// StateNotRequired defines model for stateNotRequired.
type StateNotRequired = string

// Username defines model for username.
type Username = string

// AuthenticationParams defines parameters for Authentication.
type AuthenticationParams struct {
	// ResponseType request an authorization code or or access token (implicit)
	ResponseType AuthenticationParamsResponseType `form:"response_type" json:"response_type"`

	// Scope Scope being requested
	Scope AuthenticationParamsScope `form:"scope" json:"scope"`

	// RedirectUri URI where user is redirected to after authorization
	RedirectUri RedirectUri `form:"redirect_uri" json:"redirect_uri"`

	// State This string will be echoed back to application when user is redirected
	State     *StateNotRequired `form:"state,omitempty" json:"state,omitempty"`
	ClientId  ClientId          `form:"client_id" json:"client_id"`
	ConsentId ConsentId         `form:"consentId" json:"consentId"`
}

// AuthenticationParamsResponseType defines parameters for Authentication.
type AuthenticationParamsResponseType string

// AuthenticationParamsScope defines parameters for Authentication.
type AuthenticationParamsScope string

// RedirectParams defines parameters for Redirect.
type RedirectParams struct {
	// Scope Scope being requested
	Scope            RedirectParamsScope `form:"scope" json:"scope"`
	ClientId         ClientId            `form:"client_id" json:"client_id"`
	Rstate           Rstate              `form:"rstate" json:"rstate"`
	Username         Username            `form:"username" json:"username"`
	Confirmation     Confirmation        `form:"confirmation" json:"confirmation"`
	Error            *Error              `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *ErrorDescription   `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// RedirectParamsScope defines parameters for Redirect.
type RedirectParamsScope string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Authentication request
	Authentication(ctx context.Context, params *AuthenticationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Redirect request
	Redirect(ctx context.Context, params *RedirectParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Authentication(ctx context.Context, params *AuthenticationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthenticationRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Redirect(ctx context.Context, params *RedirectParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRedirectRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthenticationRequest generates requests for Authentication
func NewAuthenticationRequest(server string, params *AuthenticationParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bridge/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "response_type", params.ResponseType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "scope", params.Scope, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "redirect_uri", params.RedirectUri, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "consentId", params.ConsentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRedirectRequest generates requests for Redirect
func NewRedirectRequest(server string, params *RedirectParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bridge/bridge_redirect")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "scope", params.Scope, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "client_id", params.ClientId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "rstate", params.Rstate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "confirmation", params.Confirmation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Error != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "error", *params.Error, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ErrorDescription != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "error_description", *params.ErrorDescription, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthenticationWithResponse request
	AuthenticationWithResponse(ctx context.Context, params *AuthenticationParams, reqEditors ...RequestEditorFn) (*AuthenticationResponse, error)

	// RedirectWithResponse request
	RedirectWithResponse(ctx context.Context, params *RedirectParams, reqEditors ...RequestEditorFn) (*RedirectResponse, error)
}

type AuthenticationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r AuthenticationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthenticationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AuthenticationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RedirectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r RedirectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RedirectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RedirectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AuthenticationWithResponse request returning *AuthenticationResponse
func (c *ClientWithResponses) AuthenticationWithResponse(ctx context.Context, params *AuthenticationParams, reqEditors ...RequestEditorFn) (*AuthenticationResponse, error) {
	rsp, err := c.Authentication(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthenticationResponse(rsp)
}

// RedirectWithResponse request returning *RedirectResponse
func (c *ClientWithResponses) RedirectWithResponse(ctx context.Context, params *RedirectParams, reqEditors ...RequestEditorFn) (*RedirectResponse, error) {
	rsp, err := c.Redirect(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRedirectResponse(rsp)
}

// ParseAuthenticationResponse parses an HTTP response from a AuthenticationWithResponse call
func ParseAuthenticationResponse(rsp *http.Response) (*AuthenticationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthenticationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRedirectResponse parses an HTTP response from a RedirectWithResponse call
func ParseRedirectResponse(rsp *http.Response) (*RedirectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RedirectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
