// Package periodicdomestic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package periodicdomestic

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// Defines values for MessageCode400PIS.
const (
	MessageCode400PISCONSENTUNKNOWN         MessageCode400PIS = "CONSENT_UNKNOWN"
	MessageCode400PISEXECUTIONDATEINVALID   MessageCode400PIS = "EXECUTION_DATE_INVALID"
	MessageCode400PISFORMATERROR            MessageCode400PIS = "FORMAT_ERROR"
	MessageCode400PISPARAMETERNOTCONSISTENT MessageCode400PIS = "PARAMETER_NOT_CONSISTENT"
	MessageCode400PISPARAMETERNOTSUPPORTED  MessageCode400PIS = "PARAMETER_NOT_SUPPORTED"
	MessageCode400PISPAYMENTFAILED          MessageCode400PIS = "PAYMENT_FAILED"
	MessageCode400PISPERIODINVALID          MessageCode400PIS = "PERIOD_INVALID"
	MessageCode400PISRESOURCEBLOCKED        MessageCode400PIS = "RESOURCE_BLOCKED"
	MessageCode400PISRESOURCEEXPIRED        MessageCode400PIS = "RESOURCE_EXPIRED"
	MessageCode400PISRESOURCEUNKNOWN        MessageCode400PIS = "RESOURCE_UNKNOWN"
	MessageCode400PISSCAMETHODUNKNOWN       MessageCode400PIS = "SCA_METHOD_UNKNOWN"
	MessageCode400PISSERVICEINVALID         MessageCode400PIS = "SERVICE_INVALID"
	MessageCode400PISTIMESTAMPINVALID       MessageCode400PIS = "TIMESTAMP_INVALID"
)

// Valid indicates whether the value is a known member of the MessageCode400PIS enum.
func (e MessageCode400PIS) Valid() bool {
	switch e {
	case MessageCode400PISCONSENTUNKNOWN:
		return true
	case MessageCode400PISEXECUTIONDATEINVALID:
		return true
	case MessageCode400PISFORMATERROR:
		return true
	case MessageCode400PISPARAMETERNOTCONSISTENT:
		return true
	case MessageCode400PISPARAMETERNOTSUPPORTED:
		return true
	case MessageCode400PISPAYMENTFAILED:
		return true
	case MessageCode400PISPERIODINVALID:
		return true
	case MessageCode400PISRESOURCEBLOCKED:
		return true
	case MessageCode400PISRESOURCEEXPIRED:
		return true
	case MessageCode400PISRESOURCEUNKNOWN:
		return true
	case MessageCode400PISSCAMETHODUNKNOWN:
		return true
	case MessageCode400PISSERVICEINVALID:
		return true
	case MessageCode400PISTIMESTAMPINVALID:
		return true
	default:
		return false
	}
}

// Defines values for MessageCode401PIS.
const (
	CERTIFICATEBLOCKED    MessageCode401PIS = "CERTIFICATE_BLOCKED"
	CERTIFICATEEXPIRED    MessageCode401PIS = "CERTIFICATE_EXPIRED"
	CERTIFICATEINVALID    MessageCode401PIS = "CERTIFICATE_INVALID"
	CERTIFICATEMISSING    MessageCode401PIS = "CERTIFICATE_MISSING"
	CERTIFICATEREVOKE     MessageCode401PIS = "CERTIFICATE_REVOKE"
	CONSENTEXPIRED        MessageCode401PIS = "CONSENT_EXPIRED"
	CONSENTINVALID        MessageCode401PIS = "CONSENT_INVALID"
	CORPORATEIDINVALID    MessageCode401PIS = "CORPORATE_ID_INVALID"
	PSUCREDENTIALSINVALID MessageCode401PIS = "PSU_CREDENTIALS_INVALID"
	REQUIREDKIDMISSING    MessageCode401PIS = "REQUIRED_KID_MISSING"
	SIGNATUREINVALID      MessageCode401PIS = "SIGNATURE_INVALID"
	SIGNATUREMISSING      MessageCode401PIS = "SIGNATURE_MISSING"
	TOKENEXPIRED          MessageCode401PIS = "TOKEN_EXPIRED"
	TOKENINVALID          MessageCode401PIS = "TOKEN_INVALID"
	TOKENUNKNOWN          MessageCode401PIS = "TOKEN_UNKNOWN"
)

// Valid indicates whether the value is a known member of the MessageCode401PIS enum.
func (e MessageCode401PIS) Valid() bool {
	switch e {
	case CERTIFICATEBLOCKED:
		return true
	case CERTIFICATEEXPIRED:
		return true
	case CERTIFICATEINVALID:
		return true
	case CERTIFICATEMISSING:
		return true
	case CERTIFICATEREVOKE:
		return true
	case CONSENTEXPIRED:
		return true
	case CONSENTINVALID:
		return true
	case CORPORATEIDINVALID:
		return true
	case PSUCREDENTIALSINVALID:
		return true
	case REQUIREDKIDMISSING:
		return true
	case SIGNATUREINVALID:
		return true
	case SIGNATUREMISSING:
		return true
	case TOKENEXPIRED:
		return true
	case TOKENINVALID:
		return true
	case TOKENUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for MessageCode403PIS.
const (
	MessageCode403PISCONSENTUNKNOWN  MessageCode403PIS = "CONSENT_UNKNOWN"
	MessageCode403PISPRODUCTINVALID  MessageCode403PIS = "PRODUCT_INVALID"
	MessageCode403PISRESOURCEEXPIRED MessageCode403PIS = "RESOURCE_EXPIRED"
	MessageCode403PISRESOURCEUNKNOWN MessageCode403PIS = "RESOURCE_UNKNOWN"
	MessageCode403PISSERVICEBLOCKED  MessageCode403PIS = "SERVICE_BLOCKED"
)

// Valid indicates whether the value is a known member of the MessageCode403PIS enum.
func (e MessageCode403PIS) Valid() bool {
	switch e {
	case MessageCode403PISCONSENTUNKNOWN:
		return true
	case MessageCode403PISPRODUCTINVALID:
		return true
	case MessageCode403PISRESOURCEEXPIRED:
		return true
	case MessageCode403PISRESOURCEUNKNOWN:
		return true
	case MessageCode403PISSERVICEBLOCKED:
		return true
	default:
		return false
	}
}

// Defines values for MessageCode404PIS.
const (
	PRODUCTUNKNOWN  MessageCode404PIS = "PRODUCT_UNKNOWN"
	RESOURCEUNKNOWN MessageCode404PIS = "RESOURCE_UNKNOWN"
)

// Valid indicates whether the value is a known member of the MessageCode404PIS enum.
func (e MessageCode404PIS) Valid() bool {
	switch e {
	case PRODUCTUNKNOWN:
		return true
	case RESOURCEUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for OtpFormat.
const (
	Characters OtpFormat = "characters"
	Integer    OtpFormat = "integer"
)

// Valid indicates whether the value is a known member of the OtpFormat enum.
func (e OtpFormat) Valid() bool {
	switch e {
	case Characters:
		return true
	case Integer:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticationType.
const (
	CHIPOTP  AuthenticationType = "CHIP_OTP"
	PHOTOOTP AuthenticationType = "PHOTO_OTP"
	PUSHOTP  AuthenticationType = "PUSH_OTP"
	SMSOTP   AuthenticationType = "SMS_OTP"
)

// Valid indicates whether the value is a known member of the AuthenticationType enum.
func (e AuthenticationType) Valid() bool {
	switch e {
	case CHIPOTP:
		return true
	case PHOTOOTP:
		return true
	case PUSHOTP:
		return true
	case SMSOTP:
		return true
	default:
		return false
	}
}

// Defines values for DayOfExecution.
const (
	N1  DayOfExecution = "1"
	N10 DayOfExecution = "10"
	N11 DayOfExecution = "11"
	N12 DayOfExecution = "12"
	N13 DayOfExecution = "13"
	N14 DayOfExecution = "14"
	N15 DayOfExecution = "15"
	N16 DayOfExecution = "16"
	N17 DayOfExecution = "17"
	N18 DayOfExecution = "18"
	N19 DayOfExecution = "19"
	N2  DayOfExecution = "2"
	N20 DayOfExecution = "20"
	N21 DayOfExecution = "21"
	N22 DayOfExecution = "22"
	N23 DayOfExecution = "23"
	N24 DayOfExecution = "24"
	N25 DayOfExecution = "25"
	N26 DayOfExecution = "26"
	N27 DayOfExecution = "27"
	N28 DayOfExecution = "28"
	N29 DayOfExecution = "29"
	N3  DayOfExecution = "3"
	N30 DayOfExecution = "30"
	N31 DayOfExecution = "31"
	N4  DayOfExecution = "4"
	N5  DayOfExecution = "5"
	N6  DayOfExecution = "6"
	N7  DayOfExecution = "7"
	N8  DayOfExecution = "8"
	N9  DayOfExecution = "9"
)

// Valid indicates whether the value is a known member of the DayOfExecution enum.
func (e DayOfExecution) Valid() bool {
	switch e {
	case N1:
		return true
	case N10:
		return true
	case N11:
		return true
	case N12:
		return true
	case N13:
		return true
	case N14:
		return true
	case N15:
		return true
	case N16:
		return true
	case N17:
		return true
	case N18:
		return true
	case N19:
		return true
	case N2:
		return true
	case N20:
		return true
	case N21:
		return true
	case N22:
		return true
	case N23:
		return true
	case N24:
		return true
	case N25:
		return true
	case N26:
		return true
	case N27:
		return true
	case N28:
		return true
	case N29:
		return true
	case N3:
		return true
	case N30:
		return true
	case N31:
		return true
	case N4:
		return true
	case N5:
		return true
	case N6:
		return true
	case N7:
		return true
	case N8:
		return true
	case N9:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionRule.
const (
	Following ExecutionRule = "following"
	Preceding ExecutionRule = "preceding"
)

// Valid indicates whether the value is a known member of the ExecutionRule enum.
func (e ExecutionRule) Valid() bool {
	switch e {
	case Following:
		return true
	case Preceding:
		return true
	default:
		return false
	}
}

// Defines values for FrequencyCode.
const (
	Annual         FrequencyCode = "Annual"
	Daily          FrequencyCode = "Daily"
	EveryTwoMonths FrequencyCode = "EveryTwoMonths"
	EveryTwoWeeks  FrequencyCode = "EveryTwoWeeks"
	Monthly        FrequencyCode = "Monthly"
	Quarterly      FrequencyCode = "Quarterly"
	SemiAnnual     FrequencyCode = "SemiAnnual"
	Weekly         FrequencyCode = "Weekly"
)

// Valid indicates whether the value is a known member of the FrequencyCode enum.
func (e FrequencyCode) Valid() bool {
	switch e {
	case Annual:
		return true
	case Daily:
		return true
	case EveryTwoMonths:
		return true
	case EveryTwoWeeks:
		return true
	case Monthly:
		return true
	case Quarterly:
		return true
	case SemiAnnual:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// Defines values for PaymentInitationRequestResponse201ServiceLevel.
const (
	NEXT PaymentInitationRequestResponse201ServiceLevel = "NEXT"
	NURG PaymentInitationRequestResponse201ServiceLevel = "NURG"
	SDVA PaymentInitationRequestResponse201ServiceLevel = "SDVA"
	SEPA PaymentInitationRequestResponse201ServiceLevel = "SEPA"
	SPOT PaymentInitationRequestResponse201ServiceLevel = "SPOT"
	URGP PaymentInitationRequestResponse201ServiceLevel = "URGP"
)

// Valid indicates whether the value is a known member of the PaymentInitationRequestResponse201ServiceLevel enum.
func (e PaymentInitationRequestResponse201ServiceLevel) Valid() bool {
	switch e {
	case NEXT:
		return true
	case NURG:
		return true
	case SDVA:
		return true
	case SEPA:
		return true
	case SPOT:
		return true
	case URGP:
		return true
	default:
		return false
	}
}

// Defines values for TppMessageCategory.
const (
	ERROR   TppMessageCategory = "ERROR"
	WARNING TppMessageCategory = "WARNING"
)

// Valid indicates whether the value is a known member of the TppMessageCategory enum.
func (e TppMessageCategory) Valid() bool {
	switch e {
	case ERROR:
		return true
	case WARNING:
		return true
	default:
		return false
	}
}

// Defines values for TransactionStatus.
const (
	ACCC TransactionStatus = "ACCC"
	ACCP TransactionStatus = "ACCP"
	ACFC TransactionStatus = "ACFC"
	ACSC TransactionStatus = "ACSC"
	ACSP TransactionStatus = "ACSP"
	ACTC TransactionStatus = "ACTC"
	ACWC TransactionStatus = "ACWC"
	ACWP TransactionStatus = "ACWP"
	CANC TransactionStatus = "CANC"
	PATC TransactionStatus = "PATC"
	PDNG TransactionStatus = "PDNG"
	RCVD TransactionStatus = "RCVD"
	RJCT TransactionStatus = "RJCT"
)

// Valid indicates whether the value is a known member of the TransactionStatus enum.
func (e TransactionStatus) Valid() bool {
	switch e {
	case ACCC:
		return true
	case ACCP:
		return true
	case ACFC:
		return true
	case ACSC:
		return true
	case ACSP:
		return true
	case ACTC:
		return true
	case ACWC:
		return true
	case ACWP:
		return true
	case CANC:
		return true
	case PATC:
		return true
	case PDNG:
		return true
	case RCVD:
		return true
	case RJCT:
		return true
	default:
		return false
	}
}

// Defines values for InitiateDomesticPaymentParamsTPPRedirectPreferred.
const (
	InitiateDomesticPaymentParamsTPPRedirectPreferredFalse InitiateDomesticPaymentParamsTPPRedirectPreferred = "false"
	InitiateDomesticPaymentParamsTPPRedirectPreferredTrue  InitiateDomesticPaymentParamsTPPRedirectPreferred = "true"
)

// Valid indicates whether the value is a known member of the InitiateDomesticPaymentParamsTPPRedirectPreferred enum.
func (e InitiateDomesticPaymentParamsTPPRedirectPreferred) Valid() bool {
	switch e {
	case InitiateDomesticPaymentParamsTPPRedirectPreferredFalse:
		return true
	case InitiateDomesticPaymentParamsTPPRedirectPreferredTrue:
		return true
	default:
		return false
	}
}

// Defines values for InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred.
const (
	InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferredFalse InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred = "false"
	InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferredTrue  InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred = "true"
)

// Valid indicates whether the value is a known member of the InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred enum.
func (e InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred) Valid() bool {
	switch e {
	case InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferredFalse:
		return true
	case InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferredTrue:
		return true
	default:
		return false
	}
}

// Defines values for InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred.
const (
	False InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred = "false"
	True  InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred = "true"
)

// Valid indicates whether the value is a known member of the InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred enum.
func (e InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for InitiateDomesticPaymentParamsPSUHttpMethod.
const (
	DELETE InitiateDomesticPaymentParamsPSUHttpMethod = "DELETE"
	GET    InitiateDomesticPaymentParamsPSUHttpMethod = "GET"
	PATCH  InitiateDomesticPaymentParamsPSUHttpMethod = "PATCH"
	POST   InitiateDomesticPaymentParamsPSUHttpMethod = "POST"
	PUT    InitiateDomesticPaymentParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the InitiateDomesticPaymentParamsPSUHttpMethod enum.
func (e InitiateDomesticPaymentParamsPSUHttpMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for InitiateDomesticPaymentParamsPaymentService.
const (
	PeriodicPayments InitiateDomesticPaymentParamsPaymentService = "periodic-payments"
)

// Valid indicates whether the value is a known member of the InitiateDomesticPaymentParamsPaymentService enum.
func (e InitiateDomesticPaymentParamsPaymentService) Valid() bool {
	switch e {
	case PeriodicPayments:
		return true
	default:
		return false
	}
}

// Error400NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 400.
type Error400NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage400PIS `json:"tppMessages,omitempty"`
}

// Error401NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 401.
type Error401NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage401PIS `json:"tppMessages,omitempty"`
}

// Error403NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 403.
type Error403NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage403PIS `json:"tppMessages,omitempty"`
}

// Error404NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 404.
type Error404NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage404PIS `json:"tppMessages,omitempty"`
}

// Error405NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 405.
type Error405NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage405PIS `json:"tppMessages,omitempty"`
}

// Error409NGPIS NextGenPSD2 specific definition of reporting error information in case of a HTTP error code 409.
type Error409NGPIS struct {
	// UnderscoreLinks A _link object with all availabel link types
	UnderscoreLinks *UnderscoreLinksAll `json:"_links,omitempty"`
	TppMessages     *[]TppMessage409PIS `json:"tppMessages,omitempty"`
}

// MessageCode400PIS Message codes defined for PIS for HTTP Error code 400 (BAD_REQUEST).
type MessageCode400PIS string

// MessageCode401PIS Message codes defined for PIS for HTTP Error code 401 (UNAUTHORIZED).
type MessageCode401PIS string

// MessageCode403PIS Message codes defined defined for PIS for PIS for HTTP Error code 403 (FORBIDDEN).
type MessageCode403PIS string

// MessageCode404PIS Message codes defined for PIS for HTTP Error code 404 (NOT FOUND).
type MessageCode404PIS string

// OtpFormat The format type of the OTP to be typed in. The admitted values are "characters" or "integer".
type OtpFormat string

// UnderscoreLinksAll A _link object with all availabel link types
type UnderscoreLinksAll struct {
	// Account Link to a resource
	Account *HrefType `json:"account,omitempty"`

	// AuthoriseTransaction Link to a resource
	AuthoriseTransaction *HrefType `json:"authoriseTransaction,omitempty"`

	// Balances Link to a resource
	Balances *HrefType `json:"balances,omitempty"`

	// CardAccount Link to a resource
	CardAccount *HrefType `json:"cardAccount,omitempty"`

	// CardTransactions Link to a resource
	CardTransactions *HrefType `json:"cardTransactions,omitempty"`

	// Download Link to a resource
	Download *HrefType `json:"download,omitempty"`

	// First Link to a resource
	First *HrefType `json:"first,omitempty"`

	// Last Link to a resource
	Last *HrefType `json:"last,omitempty"`

	// Next Link to a resource
	Next *HrefType `json:"next,omitempty"`

	// Previous Link to a resource
	Previous *HrefType `json:"previous,omitempty"`

	// ScaOAuth Link to a resource
	ScaOAuth *HrefType `json:"scaOAuth,omitempty"`

	// ScaRedirect Link to a resource
	ScaRedirect *HrefType `json:"scaRedirect,omitempty"`

	// ScaStatus Link to a resource
	ScaStatus *HrefType `json:"scaStatus,omitempty"`

	// SelectAuthenticationMethod Link to a resource
	SelectAuthenticationMethod *HrefType `json:"selectAuthenticationMethod,omitempty"`

	// Self Link to a resource
	Self *HrefType `json:"self,omitempty"`

	// StartAuthorisation Link to a resource
	StartAuthorisation *HrefType `json:"startAuthorisation,omitempty"`

	// StartAuthorisationWithAuthenticationMethodSelection Link to a resource
	StartAuthorisationWithAuthenticationMethodSelection *HrefType `json:"startAuthorisationWithAuthenticationMethodSelection,omitempty"`

	// StartAuthorisationWithEncryptedPsuAuthentication Link to a resource
	StartAuthorisationWithEncryptedPsuAuthentication *HrefType `json:"startAuthorisationWithEncryptedPsuAuthentication,omitempty"`

	// StartAuthorisationWithProprietaryData Link to a resource
	StartAuthorisationWithProprietaryData *HrefType `json:"startAuthorisationWithProprietaryData,omitempty"`

	// StartAuthorisationWithPsuAuthentication Link to a resource
	StartAuthorisationWithPsuAuthentication *HrefType `json:"startAuthorisationWithPsuAuthentication,omitempty"`

	// StartAuthorisationWithPsuIdentification Link to a resource
	StartAuthorisationWithPsuIdentification *HrefType `json:"startAuthorisationWithPsuIdentification,omitempty"`

	// StartAuthorisationWithTransactionAuthorisation Link to a resource
	StartAuthorisationWithTransactionAuthorisation *HrefType `json:"startAuthorisationWithTransactionAuthorisation,omitempty"`

	// Status Link to a resource
	Status *HrefType `json:"status,omitempty"`

	// TransactionDetails Link to a resource
	TransactionDetails *HrefType `json:"transactionDetails,omitempty"`

	// Transactions Link to a resource
	Transactions *HrefType `json:"transactions,omitempty"`

	// UpdateEncryptedPsuAuthentication Link to a resource
	UpdateEncryptedPsuAuthentication *HrefType `json:"updateEncryptedPsuAuthentication,omitempty"`

	// UpdateProprietaryData Link to a resource
	UpdateProprietaryData *HrefType `json:"updateProprietaryData,omitempty"`

	// UpdatePsuAuthentication Link to a resource
	UpdatePsuAuthentication *HrefType `json:"updatePsuAuthentication,omitempty"`

	// UpdatePsuIdentification Link to a resource
	UpdatePsuIdentification *HrefType `json:"updatePsuIdentification,omitempty"`
}

// UnderscoreLinksPaymentInitiation A list of hyperlinks to be recognised by the TPP.The actual
// hyperlinks used in the response depend on the dynamical decisions of the
// ASPSP whenprocessing the request.**Remark:** All links can be relative
// or full links, to be decided by the ASPSP.Type of links admitted in
// this response, (further links might be added for ASPSP defined extensions):
// * 'scaRedirect':   In case of an SCA Redirect Approach, the ASPSP is transmitting
// the link to which to redirect the PSU browser.* 'scaOAuth':   In case
// of a SCA OAuth2 Approach, the ASPSP is transmitting the URI where the configuration
// of the Authorisation  Server can be retrieved. The configuration follows
// the OAuth 2.0 Authorisation Server Metadata specification.* 'startAuthorisation':
// In case, where an explicit start of the transaction authorisation is
// needed, but no more data needs to be updated   (no authentication method
// to be selected, no PSU identification nor PSU authentication data to be
// uploaded).* 'startAuthorisationWithPsuIdentification':   The link to
// the authorisation end-point, where the authorisation sub-resource has to
// be generated while   uploading the PSU identification data.* 'startAuthorisationWithPsuAuthentication':
//
//	The link to the authorisation end-point, where the authorisation sub-resource
//
// has to be generated while   uploading the PSU authentication data.
// * 'startAuthorisationWithEncryptedPsuAuthentication':    Same as startAuthorisactionWithPsuAuthentication
// where the authentication data need to be encrypted on     application
// layer in uploading.* 'startAuthorisationWithAuthenticationMethodSelection':
//
//	The link to the authorisation end-point, where the authorisation sub-resource
//
// has to be generated while   selecting the authentication method.   This
// link is contained under exactly the same conditions as the data element
// "scaMethods"* 'startAuthorisationWithTransactionAuthorisation':  The
// link to the authorisation end-point, where the authorisation sub-resource
// has to be generated while   authorising the transaction e.g. by uploading
// an OTP received by SMS.* 'self':   The link to the payment initiation
// resource created by this request.  This link can be used to retrieve the
// resource data.* 'status':   The link to retrieve the transaction status
// of the payment initiation.* 'scaStatus':   The link to retrieve the
// scaStatus of the corresponding authorisation sub-resource.   This link
// is only contained, if an authorisation sub-resource has been already created.
type UnderscoreLinksPaymentInitiation struct {
	// ScaOAuth Link to a resource
	ScaOAuth *HrefType `json:"scaOAuth,omitempty"`

	// ScaRedirect Link to a resource
	ScaRedirect *HrefType `json:"scaRedirect,omitempty"`

	// ScaStatus Link to a resource
	ScaStatus *HrefType `json:"scaStatus,omitempty"`

	// Self Link to a resource
	Self *HrefType `json:"self,omitempty"`

	// StartAuthorisation Link to a resource
	StartAuthorisation *HrefType `json:"startAuthorisation,omitempty"`

	// StartAuthorisationWithAuthenticationMethodSelection Link to a resource
	StartAuthorisationWithAuthenticationMethodSelection *HrefType `json:"startAuthorisationWithAuthenticationMethodSelection,omitempty"`

	// StartAuthorisationWithEncryptedPsuAuthentication Link to a resource
	StartAuthorisationWithEncryptedPsuAuthentication *HrefType `json:"startAuthorisationWithEncryptedPsuAuthentication,omitempty"`

	// StartAuthorisationWithPsuAuthentication Link to a resource
	StartAuthorisationWithPsuAuthentication *HrefType `json:"startAuthorisationWithPsuAuthentication,omitempty"`

	// StartAuthorisationWithPsuIdentification Link to a resource
	StartAuthorisationWithPsuIdentification *HrefType `json:"startAuthorisationWithPsuIdentification,omitempty"`

	// StartAuthorisationWithTransactionAuthorisation Link to a resource
	StartAuthorisationWithTransactionAuthorisation *HrefType `json:"startAuthorisationWithTransactionAuthorisation,omitempty"`

	// Status Link to a resource
	Status *HrefType `json:"status,omitempty"`
}

// AccountReferenceDomestic IBAN, of a payment accounts
type AccountReferenceDomestic struct {
	// Currency ISO 4217 Alpha 3 currency code
	Currency *CurrencyCode `json:"currency,omitempty"`

	// Iban IBAN of an account
	Iban *string `json:"iban,omitempty"`
}

// Address defines model for address.
type Address struct {
	BuildingNumber *string `json:"buildingNumber,omitempty"`
	City           *string `json:"city,omitempty"`

	// Country ISO 3166 ALPHA2 country code
	Country    string  `json:"country"`
	PostalCode *string `json:"postalCode,omitempty"`
	Street     *string `json:"street,omitempty"`
}

// Amount defines model for amount.
type Amount struct {
	// Amount The amount given with fractional digits, where fractions must be compliant to the currency definition.
	// Up to 14 significant figures. Negative amounts are signed by minus.
	// The decimal separator is a dot.
	//
	// **Example:**
	// Valid representations for EUR with up to two decimals are:
	//
	//   * 1056
	//   * 5768.2
	//   * -1.50
	//   * 5877.78
	Amount string `json:"amount"`

	// Currency ISO 4217 Alpha 3 currency code
	Currency string `json:"currency"`
}

// AuthenticationObject Authentication Object
type AuthenticationObject struct {
	// AuthenticationMethodId An identification provided by the ASPSP for the later identification of the authentication method selection.
	AuthenticationMethodId string `json:"authenticationMethodId"`

	// AuthenticationType Type of the authentication method.More authentication types
	// might be added during implementation projects and documented in the ASPSP
	// documentation.  - 'SMS_OTP': An SCA method, where an OTP linked to the
	// transaction to be authorised is sent to the PSU through a SMS channel.
	//  - 'CHIP_OTP': An SCA method, where an OTP is generated by a chip card,
	// e.g. an TOP derived from an EMV cryptogram.     To contact the card, the
	// PSU normally needs a (handheld) device.     With this device, the PSU
	// either reads the challenging data through a visual interface like flickering
	// or     the PSU types in the challenge through the device key pad.
	//   The device then derives an OTP from the challenge data and displays the
	// OTP to the PSU.  - 'PHOTO_OTP': An SCA method, where the challenge is
	// a QR code or similar encoded visual data     which can be read in by a
	// consumer device or specific mobile app.     The device resp. the specific
	// app than derives an OTP from the visual challenge data and displays
	//   the OTP to the PSU.  - 'PUSH_OTP': An OTP is pushed to a dedicated authentication
	// APP and displayed to the PSU.
	AuthenticationType AuthenticationType `json:"authenticationType"`

	// AuthenticationVersion Depending on the "authenticationType".
	// This version can be used by differentiating authentication tools used within performing OTP generation in the same authentication type.
	// This version can be referred to in the ASPSP?s documentation.
	AuthenticationVersion *string `json:"authenticationVersion,omitempty"`

	// Explanation Detailed information about the SCA method for the PSU.
	Explanation *string `json:"explanation,omitempty"`

	// Name This is the name of the authentication method defined by the PSU in the Online Banking frontend of the ASPSP.
	// Alternatively this could be a description provided by the ASPSP like "SMS OTP on phone +49160 xxxxx 28".
	// This name shall be used by the TPP when presenting a list of authentication methods to the PSU, if available.
	Name *string `json:"name,omitempty"`
}

// AuthenticationType Type of the authentication method.More authentication types
// might be added during implementation projects and documented in the ASPSP
// documentation.  - 'SMS_OTP': An SCA method, where an OTP linked to the
// transaction to be authorised is sent to the PSU through a SMS channel.
//   - 'CHIP_OTP': An SCA method, where an OTP is generated by a chip card,
//
// e.g. an TOP derived from an EMV cryptogram.     To contact the card, the
// PSU normally needs a (handheld) device.     With this device, the PSU
// either reads the challenging data through a visual interface like flickering
// or     the PSU types in the challenge through the device key pad.
//
//	The device then derives an OTP from the challenge data and displays the
//
// OTP to the PSU.  - 'PHOTO_OTP': An SCA method, where the challenge is
// a QR code or similar encoded visual data     which can be read in by a
// consumer device or specific mobile app.     The device resp. the specific
// app than derives an OTP from the visual challenge data and displays
//
//	the OTP to the PSU.  - 'PUSH_OTP': An OTP is pushed to a dedicated authentication
//
// APP and displayed to the PSU.
type AuthenticationType string

// ChallengeData It is contained in addition to the data element 'chosenScaMethod' if challenge data is needed for SCA.
// In rare cases this attribute is also used in the context of the 'startAuthorisationWithPsuAuthentication' link.
type ChallengeData struct {
	// AdditionalInformation Additional explanation for the PSU to explain
	// e.g. fallback mechanism for the chosen SCA method.
	// The TPP is obliged to show this to the PSU.
	AdditionalInformation *string `json:"additionalInformation,omitempty"`

	// Data String challenge data
	Data *string `json:"data,omitempty"`

	// Image PNG data (max. 512 kilobyte) to be displayed to the PSU,
	// Base64 encoding, cp. [RFC4648].
	// This attribute is used only, when PHOTO_OTP or CHIP_OTP
	// is the selected SCA method.
	Image *string `json:"image,omitempty"`

	// ImageLink A link where the ASPSP will provides the challenge image for the TPP.
	ImageLink *string `json:"imageLink,omitempty"`

	// OtpFormat The format type of the OTP to be typed in. The admitted values are "characters" or "integer".
	OtpFormat *OtpFormat `json:"otpFormat,omitempty"`

	// OtpMaxLength The maximal length for the OTP to be typed in by the PSU.
	OtpMaxLength *int32 `json:"otpMaxLength,omitempty"`
}

// CreditorAgentName Creditor Agent Name
type CreditorAgentName = string

// CurrencyCode ISO 4217 Alpha 3 currency code
type CurrencyCode = string

// DayOfExecution Day of execution as string.
//
// This string consists of up two characters.
// Leading zeroes are not allowed.
//
// 31 is ultimo of the month.
type DayOfExecution string

// EndDate The last applicable day of execution. If not given, it is an infinite standing order.
type EndDate = openapi_types.Date

// ExecutionRule "following" or "preceding" supported as values.
// This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday.
// The payment is then executed either the "preceding" or "following" working day.
// ASPSP might reject the request due to the communicated value, if rules in Online-Banking are not supporting
// this execution rule.
type ExecutionRule string

// Frequency The following codes from the "EventFrequency7Code" of ISO 20022 are supported.
// - "Daily"
// - "Weekly"
// - "EveryTwoWeeks"
// - "Monthly"
// - "EveryTwoMonths"
// - "Quarterly"
// - "SemiAnnual"
// - "Annual"
type Frequency = FrequencyCode

// FrequencyCode The following codes from the "EventFrequency7Code" of ISO 20022 are supported.
// - "Daily"
// - "Weekly"
// - "EveryTwoWeeks"
// - "Monthly"
// - "EveryTwoMonths"
// - "Quarterly"
// - "SemiAnnual"
// - "Annual"
type FrequencyCode string

// HrefEntry Link to a resource
type HrefEntry = string

// HrefType Link to a resource
type HrefType struct {
	// Href Link to a resource
	Href *HrefEntry `json:"href,omitempty"`
}

// InformationStructured defines model for informationStructured.
type InformationStructured struct {
	// Reference The actual reference.
	Reference *string `json:"reference,omitempty"`

	// ReferenceIssuer referenceIssuer
	ReferenceIssuer *string `json:"referenceIssuer,omitempty"`

	// ReferenceType referenceType
	ReferenceType *string `json:"referenceType,omitempty"`
}

// PaymentInitationRequestResponse201 Body of the response for a successful payment initiation request.
type PaymentInitationRequestResponse201 struct {
	// UnderscoreLinks A list of hyperlinks to be recognised by the TPP.The actual
	// hyperlinks used in the response depend on the dynamical decisions of the
	// ASPSP whenprocessing the request.**Remark:** All links can be relative
	// or full links, to be decided by the ASPSP.Type of links admitted in
	// this response, (further links might be added for ASPSP defined extensions):
	// * 'scaRedirect':   In case of an SCA Redirect Approach, the ASPSP is transmitting
	// the link to which to redirect the PSU browser.* 'scaOAuth':   In case
	// of a SCA OAuth2 Approach, the ASPSP is transmitting the URI where the configuration
	// of the Authorisation  Server can be retrieved. The configuration follows
	// the OAuth 2.0 Authorisation Server Metadata specification.* 'startAuthorisation':
	// In case, where an explicit start of the transaction authorisation is
	// needed, but no more data needs to be updated   (no authentication method
	// to be selected, no PSU identification nor PSU authentication data to be
	// uploaded).* 'startAuthorisationWithPsuIdentification':   The link to
	// the authorisation end-point, where the authorisation sub-resource has to
	// be generated while   uploading the PSU identification data.* 'startAuthorisationWithPsuAuthentication':
	//   The link to the authorisation end-point, where the authorisation sub-resource
	// has to be generated while   uploading the PSU authentication data.
	// * 'startAuthorisationWithEncryptedPsuAuthentication':    Same as startAuthorisactionWithPsuAuthentication
	// where the authentication data need to be encrypted on     application
	// layer in uploading.* 'startAuthorisationWithAuthenticationMethodSelection':
	//   The link to the authorisation end-point, where the authorisation sub-resource
	// has to be generated while   selecting the authentication method.   This
	// link is contained under exactly the same conditions as the data element
	// "scaMethods"* 'startAuthorisationWithTransactionAuthorisation':  The
	// link to the authorisation end-point, where the authorisation sub-resource
	// has to be generated while   authorising the transaction e.g. by uploading
	// an OTP received by SMS.* 'self':   The link to the payment initiation
	// resource created by this request.  This link can be used to retrieve the
	// resource data.* 'status':   The link to retrieve the transaction status
	// of the payment initiation.* 'scaStatus':   The link to retrieve the
	// scaStatus of the corresponding authorisation sub-resource.   This link
	// is only contained, if an authorisation sub-resource has been already created.
	UnderscoreLinks UnderscoreLinksPaymentInitiation `json:"_links"`

	// ChallengeData It is contained in addition to the data element 'chosenScaMethod' if challenge data is needed for SCA.
	// In rare cases this attribute is also used in the context of the 'startAuthorisationWithPsuAuthentication' link.
	ChallengeData *ChallengeData `json:"challengeData,omitempty"`

	// ChosenScaMethod Authentication Object
	ChosenScaMethod *AuthenticationObject `json:"chosenScaMethod,omitempty"`

	// CreditorAgentName Creditor Agent Name
	CreditorAgentName      *CreditorAgentName `json:"creditorAgentName,omitempty"`
	EndToEndIdentification *string            `json:"endToEndIdentification,omitempty"`

	// PaymentId Resource identification of the generated payment initiation resource.
	PaymentId string `json:"paymentId"`

	// PsuMessage Text to be displayed to the PSU
	PsuMessage *string `json:"psuMessage,omitempty"`

	// ScaMethods This data element might be contained, if SCA is required and if the PSU has a choice between different
	// authentication methods.
	//
	// Depending on the risk management of the ASPSP this choice might be offered before or after the PSU
	// has been identified with the first relevant factor, or if an access token is transported.
	//
	// If this data element is contained, then there is also an hyperlink of type 'startAuthorisationWithAuthenticationMethodSelection'
	// contained in the response body.
	//
	// These methods shall be presented towards the PSU for selection by the TPP.
	ScaMethods   *[]AuthenticationObject                         `json:"scaMethods,omitempty"`
	ServiceLevel *PaymentInitationRequestResponse201ServiceLevel `json:"serviceLevel,omitempty"`
	TppMessages  *[]TppMessage2XX                                `json:"tppMessages,omitempty"`

	// TransactionFeeIndicator If equals 'true', the transaction will involve specific transaction cost as shown by the ASPSP in
	// their public price list or as agreed between ASPSP and PSU.
	// If equals 'false', the transaction will not involve additional specific transaction costs to the PSU.
	TransactionFeeIndicator *bool   `json:"transactionFeeIndicator,omitempty"`
	TransactionFees         *Amount `json:"transactionFees,omitempty"`

	// TransactionStatus The transaction status is filled with codes of the ISO 20022 data
	// table:- 'ACCC': 'AcceptedSettlementCompleted' -  Settlement on the creditor's
	// account has been completed.- 'ACCP': 'AcceptedCustomerProfile' -   Preceding
	// check of technical validation was successful.   Customer profile check
	// was also successful.- 'ACSC': 'AcceptedSettlementCompleted' -   Settlement
	// on the debtor?s account has been completed.    **Usage:** this can be
	// used by the first agent to report to the debtor that the transaction has
	// been completed.     **Warning:** this status is provided for transaction
	// status reasons, not for financial information.   It can only be used after
	// bilateral agreement.- 'ACSP': 'AcceptedSettlementInProcess' -   All
	// preceding checks such as technical validation and customer profile were
	// successful and therefore the payment initiation has been accepted for execution.
	// ACTC': 'AcceptedTechnicalValidation' -   Authentication and syntactical
	// and semantical validation are successful.- 'ACWC': 'AcceptedWithChange'
	// -   Instruction is accepted but a change will be made, such as date or
	// remittance not sent.- 'ACWP': 'AcceptedWithoutPosting' -   Payment instruction
	// included in the credit transfer is accepted without being posted to the
	// creditor customer?s account.- 'RCVD': 'Received' -   Payment initiation
	// has been received by the receiving agent.- 'PDNG': 'Pending' -   Payment
	// initiation or individual transaction included in the payment initiation
	// is pending.   Further checks and status update will be performed.- 'RJCT':
	// 'Rejected' -   Payment initiation or individual transaction included in
	// the payment initiation has been rejected.- 'CANC': 'Cancelled'  Payment
	// initiation has been cancelled before execution  Remark: This code is still
	// requested from ISO20022.- 'ACFC': 'AcceptedFundsChecked' -  Preceeding
	// check of technical validation and customer profile was successful and an
	// automatic funds check was positive .  Remark: This code is still requested
	// from ISO20022.- 'PATC': 'PartiallyAcceptedTechnical'  Correct The payment
	// initiation needs multiple authentications, where some but not yet all have
	// been performed. Syntactical and semantical validations are successful.
	// Remark: This code is still requested from ISO20022.
	TransactionStatus TransactionStatus `json:"transactionStatus"`
}

// PaymentInitationRequestResponse201ServiceLevel defines model for PaymentInitationRequestResponse201.ServiceLevel.
type PaymentInitationRequestResponse201ServiceLevel string

// PaymentInitiationDomesticJson Body for a periodic payment initiation.
type PaymentInitiationDomesticJson struct {
	// CreditorAccount IBAN, of a payment accounts
	CreditorAccount AccountReferenceDomestic `json:"creditorAccount"`
	CreditorAddress *Address                 `json:"creditorAddress,omitempty"`

	// CreditorAgent BICFI
	CreditorAgent *string `json:"creditorAgent,omitempty"`

	// CreditorName Creditor Name
	CreditorName string `json:"creditorName"`

	// DayOfExecution Day of execution as string.
	//
	// This string consists of up two characters.
	// Leading zeroes are not allowed.
	//
	// 31 is ultimo of the month.
	DayOfExecution *DayOfExecution `json:"dayOfExecution,omitempty"`

	// DebtorAccount IBAN, of a payment accounts
	DebtorAccount AccountReferenceDomestic `json:"debtorAccount"`

	// EndDate The last applicable day of execution. If not given, it is an infinite standing order.
	EndDate *EndDate `json:"endDate,omitempty"`

	// ExecutionRule "following" or "preceding" supported as values.
	// This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday.
	// The payment is then executed either the "preceding" or "following" working day.
	// ASPSP might reject the request due to the communicated value, if rules in Online-Banking are not supporting
	// this execution rule.
	ExecutionRule *ExecutionRule `json:"executionRule,omitempty"`

	// Frequency The following codes from the "EventFrequency7Code" of ISO 20022 are supported.
	// - "Daily"
	// - "Weekly"
	// - "EveryTwoWeeks"
	// - "Monthly"
	// - "EveryTwoMonths"
	// - "Quarterly"
	// - "SemiAnnual"
	// - "Annual"
	Frequency                         Frequency              `json:"frequency"`
	InstructedAmount                  Amount                 `json:"instructedAmount"`
	PurposeCode                       *string                `json:"purposeCode,omitempty"`
	RemittanceInformationStructured   *InformationStructured `json:"remittanceInformationStructured,omitempty"`
	RemittanceInformationUnstructured *string                `json:"remittanceInformationUnstructured,omitempty"`
	RequestedExecutionDate            *openapi_types.Date    `json:"requestedExecutionDate,omitempty"`

	// StartDate The first applicable day of execution starting from this date is the first payment.
	StartDate StartDate `json:"startDate"`

	// UltimateCreditor Max size 70 chars
	UltimateCreditor *string `json:"ultimateCreditor,omitempty"`

	// UltimateDebtor Max size 70 chars
	UltimateDebtor *string `json:"ultimateDebtor,omitempty"`
}

// StartDate The first applicable day of execution starting from this date is the first payment.
type StartDate = openapi_types.Date

// TppMessage2XX defines model for tppMessage2XX.
type TppMessage2XX struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes for HTTP Error codes 2XX.
	Code string  `json:"code"`
	Path *string `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage400PIS defines model for tppMessage400_PIS.
type TppMessage400PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined for PIS for HTTP Error code 400 (BAD_REQUEST).
	Code MessageCode400PIS `json:"code"`
	Path *string           `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage401PIS defines model for tppMessage401_PIS.
type TppMessage401PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined for PIS for HTTP Error code 401 (UNAUTHORIZED).
	Code MessageCode401PIS `json:"code"`
	Path *string           `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage403PIS defines model for tppMessage403_PIS.
type TppMessage403PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined defined for PIS for PIS for HTTP Error code 403 (FORBIDDEN).
	Code MessageCode403PIS `json:"code"`
	Path *string           `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage404PIS defines model for tppMessage404_PIS.
type TppMessage404PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined for PIS for HTTP Error code 404 (NOT FOUND).
	Code MessageCode404PIS `json:"code"`
	Path *string           `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage405PIS defines model for tppMessage405_PIS.
type TppMessage405PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined for payment cancelations PIS for HTTP Error code 405 (METHOD NOT ALLOWED).
	Code string  `json:"code"`
	Path *string `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessage409PIS defines model for tppMessage409_PIS.
type TppMessage409PIS struct {
	// Category Category of the TPP message category
	Category TppMessageCategory `json:"category"`

	// Code Message codes defined for PIS for HTTP Error code 409 (CONFLICT).
	Code string  `json:"code"`
	Path *string `json:"path,omitempty"`

	// Text Additional explaining text to the TPP.
	Text *string `json:"text,omitempty"`
}

// TppMessageCategory Category of the TPP message category
type TppMessageCategory string

// TransactionStatus The transaction status is filled with codes of the ISO 20022 data
// table:- 'ACCC': 'AcceptedSettlementCompleted' -  Settlement on the creditor's
// account has been completed.- 'ACCP': 'AcceptedCustomerProfile' -   Preceding
// check of technical validation was successful.   Customer profile check
// was also successful.- 'ACSC': 'AcceptedSettlementCompleted' -   Settlement
// on the debtor?s account has been completed.    **Usage:** this can be
// used by the first agent to report to the debtor that the transaction has
// been completed.     **Warning:** this status is provided for transaction
// status reasons, not for financial information.   It can only be used after
// bilateral agreement.- 'ACSP': 'AcceptedSettlementInProcess' -   All
// preceding checks such as technical validation and customer profile were
// successful and therefore the payment initiation has been accepted for execution.
// ACTC': 'AcceptedTechnicalValidation' -   Authentication and syntactical
// and semantical validation are successful.- 'ACWC': 'AcceptedWithChange'
// -   Instruction is accepted but a change will be made, such as date or
// remittance not sent.- 'ACWP': 'AcceptedWithoutPosting' -   Payment instruction
// included in the credit transfer is accepted without being posted to the
// creditor customer?s account.- 'RCVD': 'Received' -   Payment initiation
// has been received by the receiving agent.- 'PDNG': 'Pending' -   Payment
// initiation or individual transaction included in the payment initiation
// is pending.   Further checks and status update will be performed.- 'RJCT':
// 'Rejected' -   Payment initiation or individual transaction included in
// the payment initiation has been rejected.- 'CANC': 'Cancelled'  Payment
// initiation has been cancelled before execution  Remark: This code is still
// requested from ISO20022.- 'ACFC': 'AcceptedFundsChecked' -  Preceeding
// check of technical validation and customer profile was successful and an
// automatic funds check was positive .  Remark: This code is still requested
// from ISO20022.- 'PATC': 'PartiallyAcceptedTechnical'  Correct The payment
// initiation needs multiple authentications, where some but not yet all have
// been performed. Syntactical and semantical validations are successful.
// Remark: This code is still requested from ISO20022.
type TransactionStatus string

// Digest defines model for digest.
type Digest = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// InitiateDomesticPaymentParams defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID openapi_types.UUID `json:"X-Request-ID"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding http request IP Address field between PSU and TPP.
	PSUIPAddress string `json:"PSU-IP-Address"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUID Client ID of the PSU in the ASPSP client interface. Might be mandated in the ASPSP's documentation.
	// Is not contained if an OAuth2 based authentication was performed in a pre-step or an OAuth2 based SCA was performed in an preceeding
	// AIS service in the same session.
	PSUID *string `json:"PSU-ID,omitempty"`

	// PSUIDType Type of the PSU-ID, needed in scenarios where PSUs have several PSU-IDs as access possibility.
	PSUIDType *string `json:"PSU-ID-Type,omitempty"`

	// PSUCorporateID Might be mandated in the ASPSP's documentation. Only used in a corporate context.
	PSUCorporateID *string `json:"PSU-Corporate-ID,omitempty"`

	// PSUCorporateIDType Might be mandated in the ASPSP's documentation. Only used in a corporate context.
	PSUCorporateIDType *string `json:"PSU-Corporate-ID-Type,omitempty"`

	// ConsentID This data element may be contained, if the payment initiation transaction is part of a session, i.e. combined AIS/PIS service.
	// This then contains the consentId of the related AIS consent, which was performed prior to this payment initiation.
	ConsentID *string `json:"Consent-ID,omitempty"`

	// TPPRedirectPreferred If it equals "true", the TPP prefers a redirect over an embedded SCA approach.
	// If it equals "false", the TPP prefers not to be redirected for SCA. The ASPSP will then choose between the Embedded or the Decoupled
	// SCA approach, depending on the choice of the SCA procedure by the TPP/PSU.
	// If the parameter is not used, the ASPSP will choose the SCA approach to be applied depending on the SCA method chosen by the
	// TPP/PSU.
	TPPRedirectPreferred *InitiateDomesticPaymentParamsTPPRedirectPreferred `json:"TPP-Redirect-Preferred,omitempty"`

	// TPPRedirectURI URI of the TPP, where the transaction flow shall be redirected
	// to after a Redirect.Mandated for the Redirect SCA Approach (including
	// OAuth2 SCA approach), specifically when TPP-Redirect-Preferred equals
	// "true".It is recommended to always use this header field. **Remark
	// for Future:** This field might be changed to mandatory in the next version
	// of the specification.
	TPPRedirectURI *string `json:"TPP-Redirect-URI,omitempty"`

	// TPPNokRedirectURI If this URI is contained, the TPP is asking to redirect the transaction flow to this address instead of the TPP-Redirect-URI in case
	// of a negative result of the redirect SCA method. This might be ignored by the ASPSP.
	TPPNokRedirectURI *string `json:"TPP-Nok-Redirect-URI,omitempty"`

	// TPPExplicitAuthorisationPreferred If it equals "true", the TPP prefers to start the authorisation
	// process separately, e.g. because of the usage of a signing basket.
	// This preference might be ignored by the ASPSP, if a signing basket is not
	// supported as functionality.If it equals "false" or if the parameter
	// is not used, there is no preference of the TPP. This especially indicates
	// that the TPP assumes a direct authorisation of the transaction in the
	// next step, without using a signing basket.
	TPPExplicitAuthorisationPreferred *InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred `json:"TPP-Explicit-Authorisation-Preferred,omitempty"`

	// TPPRejectionNoFundsPreferred If it equals "true" then the TPP prefers a rejection of the payment initiation in case the ASPSP is providing an integrated confirmation of funds request an the result of this is that not sufficient funds are available. If it equals "false" then the TPP prefers that the ASPSP is dealing with the payment initiation like in the ASPSPs online channel, potentially waiting for a certain time period for funds to arrive to initiate the payment.This parameter might be ignored by the ASPSP.
	TPPRejectionNoFundsPreferred *InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred `json:"TPP-Rejection-NoFunds-Preferred,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *string `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *string `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *string `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *string `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *string `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between PSU and TPP, if available.
	PSUUserAgent *string `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *InitiateDomesticPaymentParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *openapi_types.UUID `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *string `json:"PSU-Geo-Location,omitempty"`
}

// InitiateDomesticPaymentParamsTPPRedirectPreferred defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParamsTPPRedirectPreferred string

// InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParamsTPPExplicitAuthorisationPreferred string

// InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParamsTPPRejectionNoFundsPreferred string

// InitiateDomesticPaymentParamsPSUHttpMethod defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParamsPSUHttpMethod string

// InitiateDomesticPaymentParamsPaymentService defines parameters for InitiateDomesticPayment.
type InitiateDomesticPaymentParamsPaymentService string

// InitiateDomesticPaymentJSONRequestBody defines body for InitiateDomesticPayment for application/json ContentType.
type InitiateDomesticPaymentJSONRequestBody = PaymentInitiationDomesticJson

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// InitiateDomesticPaymentWithBody request with any body
	InitiateDomesticPaymentWithBody(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitiateDomesticPayment(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, body InitiateDomesticPaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) InitiateDomesticPaymentWithBody(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitiateDomesticPaymentRequestWithBody(c.Server, paymentService, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitiateDomesticPayment(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, body InitiateDomesticPaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitiateDomesticPaymentRequest(c.Server, paymentService, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewInitiateDomesticPaymentRequest calls the generic InitiateDomesticPayment builder with application/json body
func NewInitiateDomesticPaymentRequest(server string, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, body InitiateDomesticPaymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitiateDomesticPaymentRequestWithBody(server, paymentService, params, "application/json", bodyReader)
}

// NewInitiateDomesticPaymentRequestWithBody generates requests for InitiateDomesticPayment with any type of body
func NewInitiateDomesticPaymentRequestWithBody(server string, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "paymentService", paymentService, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/domestic", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("PSU-IP-Address", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

		if params.PSUID != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID", *params.PSUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID", headerParam5)
		}

		if params.PSUIDType != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID-Type", *params.PSUIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID-Type", headerParam6)
		}

		if params.PSUCorporateID != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID", *params.PSUCorporateID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID", headerParam7)
		}

		if params.PSUCorporateIDType != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID-Type", *params.PSUCorporateIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID-Type", headerParam8)
		}

		if params.ConsentID != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", *params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Consent-ID", headerParam9)
		}

		if params.TPPRedirectPreferred != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-Preferred", *params.TPPRedirectPreferred, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-Preferred", headerParam10)
		}

		if params.TPPRedirectURI != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-URI", *params.TPPRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-URI", headerParam11)
		}

		if params.TPPNokRedirectURI != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "TPP-Nok-Redirect-URI", *params.TPPNokRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Nok-Redirect-URI", headerParam12)
		}

		if params.TPPExplicitAuthorisationPreferred != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "TPP-Explicit-Authorisation-Preferred", *params.TPPExplicitAuthorisationPreferred, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Explicit-Authorisation-Preferred", headerParam13)
		}

		if params.TPPRejectionNoFundsPreferred != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "TPP-Rejection-NoFunds-Preferred", *params.TPPRejectionNoFundsPreferred, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Rejection-NoFunds-Preferred", headerParam14)
		}

		if params.PSUIPPort != nil {
			var headerParam15 string

			headerParam15, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam15)
		}

		if params.PSUAccept != nil {
			var headerParam16 string

			headerParam16, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam16)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam17 string

			headerParam17, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam17)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam18 string

			headerParam18, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam18)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam19 string

			headerParam19, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam19)
		}

		if params.PSUUserAgent != nil {
			var headerParam20 string

			headerParam20, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam20)
		}

		if params.PSUHttpMethod != nil {
			var headerParam21 string

			headerParam21, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam21)
		}

		if params.PSUDeviceID != nil {
			var headerParam22 string

			headerParam22, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam22)
		}

		if params.PSUGeoLocation != nil {
			var headerParam23 string

			headerParam23, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam23)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// InitiateDomesticPaymentWithBodyWithResponse request with any body
	InitiateDomesticPaymentWithBodyWithResponse(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitiateDomesticPaymentResponse, error)

	InitiateDomesticPaymentWithResponse(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, body InitiateDomesticPaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*InitiateDomesticPaymentResponse, error)
}

type InitiateDomesticPaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PaymentInitationRequestResponse201
	JSON400      *Error400NGPIS
	JSON401      *Error401NGPIS
	JSON403      *Error403NGPIS
	JSON404      *Error404NGPIS
	JSON405      *Error405NGPIS
	JSON409      *Error409NGPIS
}

// Status returns HTTPResponse.Status
func (r InitiateDomesticPaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitiateDomesticPaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r InitiateDomesticPaymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// InitiateDomesticPaymentWithBodyWithResponse request with arbitrary body returning *InitiateDomesticPaymentResponse
func (c *ClientWithResponses) InitiateDomesticPaymentWithBodyWithResponse(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitiateDomesticPaymentResponse, error) {
	rsp, err := c.InitiateDomesticPaymentWithBody(ctx, paymentService, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitiateDomesticPaymentResponse(rsp)
}

func (c *ClientWithResponses) InitiateDomesticPaymentWithResponse(ctx context.Context, paymentService InitiateDomesticPaymentParamsPaymentService, params *InitiateDomesticPaymentParams, body InitiateDomesticPaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*InitiateDomesticPaymentResponse, error) {
	rsp, err := c.InitiateDomesticPayment(ctx, paymentService, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitiateDomesticPaymentResponse(rsp)
}

// ParseInitiateDomesticPaymentResponse parses an HTTP response from a InitiateDomesticPaymentWithResponse call
func ParseInitiateDomesticPaymentResponse(rsp *http.Response) (*InitiateDomesticPaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitiateDomesticPaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PaymentInitationRequestResponse201
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error400NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error401NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error403NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error404NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error405NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error409NGPIS
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
