// Package accounts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package accounts

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OAuth2Scopes         oAuth2ContextKey         = "OAuth2.Scopes"
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// Defines values for XS2ABerlinAccountCashAccountType.
const (
	CACC XS2ABerlinAccountCashAccountType = "CACC"
	SVGS XS2ABerlinAccountCashAccountType = "SVGS"
)

// Valid indicates whether the value is a known member of the XS2ABerlinAccountCashAccountType enum.
func (e XS2ABerlinAccountCashAccountType) Valid() bool {
	switch e {
	case CACC:
		return true
	case SVGS:
		return true
	default:
		return false
	}
}

// Defines values for XS2ABerlinBalanceBalanceType.
const (
	Expected         XS2ABerlinBalanceBalanceType = "expected"
	InterimAvailable XS2ABerlinBalanceBalanceType = "interimAvailable"
)

// Valid indicates whether the value is a known member of the XS2ABerlinBalanceBalanceType enum.
func (e XS2ABerlinBalanceBalanceType) Valid() bool {
	switch e {
	case Expected:
		return true
	case InterimAvailable:
		return true
	default:
		return false
	}
}

// Defines values for BookingStatus.
const (
	BookingStatusBooked  BookingStatus = "booked"
	BookingStatusBoth    BookingStatus = "both"
	BookingStatusPending BookingStatus = "pending"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case BookingStatusBooked:
		return true
	case BookingStatusBoth:
		return true
	case BookingStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PsuHttpMethod.
const (
	PsuHttpMethodDELETE PsuHttpMethod = "DELETE"
	PsuHttpMethodGET    PsuHttpMethod = "GET"
	PsuHttpMethodPATCH  PsuHttpMethod = "PATCH"
	PsuHttpMethodPOST   PsuHttpMethod = "POST"
	PsuHttpMethodPUT    PsuHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the PsuHttpMethod enum.
func (e PsuHttpMethod) Valid() bool {
	switch e {
	case PsuHttpMethodDELETE:
		return true
	case PsuHttpMethodGET:
		return true
	case PsuHttpMethodPATCH:
		return true
	case PsuHttpMethodPOST:
		return true
	case PsuHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for GetAccountListParamsPSUHttpMethod.
const (
	GetAccountListParamsPSUHttpMethodDELETE GetAccountListParamsPSUHttpMethod = "DELETE"
	GetAccountListParamsPSUHttpMethodGET    GetAccountListParamsPSUHttpMethod = "GET"
	GetAccountListParamsPSUHttpMethodPATCH  GetAccountListParamsPSUHttpMethod = "PATCH"
	GetAccountListParamsPSUHttpMethodPOST   GetAccountListParamsPSUHttpMethod = "POST"
	GetAccountListParamsPSUHttpMethodPUT    GetAccountListParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetAccountListParamsPSUHttpMethod enum.
func (e GetAccountListParamsPSUHttpMethod) Valid() bool {
	switch e {
	case GetAccountListParamsPSUHttpMethodDELETE:
		return true
	case GetAccountListParamsPSUHttpMethodGET:
		return true
	case GetAccountListParamsPSUHttpMethodPATCH:
		return true
	case GetAccountListParamsPSUHttpMethodPOST:
		return true
	case GetAccountListParamsPSUHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for GetAccountDetailsParamsPSUHttpMethod.
const (
	GetAccountDetailsParamsPSUHttpMethodDELETE GetAccountDetailsParamsPSUHttpMethod = "DELETE"
	GetAccountDetailsParamsPSUHttpMethodGET    GetAccountDetailsParamsPSUHttpMethod = "GET"
	GetAccountDetailsParamsPSUHttpMethodPATCH  GetAccountDetailsParamsPSUHttpMethod = "PATCH"
	GetAccountDetailsParamsPSUHttpMethodPOST   GetAccountDetailsParamsPSUHttpMethod = "POST"
	GetAccountDetailsParamsPSUHttpMethodPUT    GetAccountDetailsParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetAccountDetailsParamsPSUHttpMethod enum.
func (e GetAccountDetailsParamsPSUHttpMethod) Valid() bool {
	switch e {
	case GetAccountDetailsParamsPSUHttpMethodDELETE:
		return true
	case GetAccountDetailsParamsPSUHttpMethodGET:
		return true
	case GetAccountDetailsParamsPSUHttpMethodPATCH:
		return true
	case GetAccountDetailsParamsPSUHttpMethodPOST:
		return true
	case GetAccountDetailsParamsPSUHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for GetBalancesParamsPSUHttpMethod.
const (
	GetBalancesParamsPSUHttpMethodDELETE GetBalancesParamsPSUHttpMethod = "DELETE"
	GetBalancesParamsPSUHttpMethodGET    GetBalancesParamsPSUHttpMethod = "GET"
	GetBalancesParamsPSUHttpMethodPATCH  GetBalancesParamsPSUHttpMethod = "PATCH"
	GetBalancesParamsPSUHttpMethodPOST   GetBalancesParamsPSUHttpMethod = "POST"
	GetBalancesParamsPSUHttpMethodPUT    GetBalancesParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetBalancesParamsPSUHttpMethod enum.
func (e GetBalancesParamsPSUHttpMethod) Valid() bool {
	switch e {
	case GetBalancesParamsPSUHttpMethodDELETE:
		return true
	case GetBalancesParamsPSUHttpMethodGET:
		return true
	case GetBalancesParamsPSUHttpMethodPATCH:
		return true
	case GetBalancesParamsPSUHttpMethodPOST:
		return true
	case GetBalancesParamsPSUHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for GetTransactionListParamsBookingStatus.
const (
	GetTransactionListParamsBookingStatusBooked  GetTransactionListParamsBookingStatus = "booked"
	GetTransactionListParamsBookingStatusBoth    GetTransactionListParamsBookingStatus = "both"
	GetTransactionListParamsBookingStatusPending GetTransactionListParamsBookingStatus = "pending"
)

// Valid indicates whether the value is a known member of the GetTransactionListParamsBookingStatus enum.
func (e GetTransactionListParamsBookingStatus) Valid() bool {
	switch e {
	case GetTransactionListParamsBookingStatusBooked:
		return true
	case GetTransactionListParamsBookingStatusBoth:
		return true
	case GetTransactionListParamsBookingStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GetTransactionListParamsPSUHttpMethod.
const (
	DELETE GetTransactionListParamsPSUHttpMethod = "DELETE"
	GET    GetTransactionListParamsPSUHttpMethod = "GET"
	PATCH  GetTransactionListParamsPSUHttpMethod = "PATCH"
	POST   GetTransactionListParamsPSUHttpMethod = "POST"
	PUT    GetTransactionListParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetTransactionListParamsPSUHttpMethod enum.
func (e GetTransactionListParamsPSUHttpMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// XS2ABerlinAccount defines model for XS2A_Berlin_Account.
type XS2ABerlinAccount struct {
	// UnderscoreLinks Relative Links to the balances and to the Transactions
	UnderscoreLinks *struct {
		// Balances Link to a resource
		Balances *HrefType `json:"balances,omitempty"`

		// Transactions Link to a resource
		Transactions *HrefType `json:"transactions,omitempty"`
	} `json:"_links,omitempty"`

	// Balances Optional. Fetched list of balances only if the withBalance is requested in the query parameters and the consent has been granted.
	Balances *[]XS2ABerlinBalance `json:"balances,omitempty"`

	// Bic The BIC associated to the account.
	Bic *string `json:"bic,omitempty"`

	// CashAccountType CreditAccount relates to a Credit Account type. Account Type. CurrentAccount relates to a Current Account.
	CashAccountType *XS2ABerlinAccountCashAccountType `json:"cashAccountType,omitempty"`

	// Currency Account Currency
	Currency string `json:"currency"`

	// Iban Iban of the account
	Iban *string `json:"iban,omitempty"`

	// Name Account name.
	Name *string `json:"name,omitempty"`

	// OwnerName Name of the legal account owner.
	// If there is more than one owner, then e.g. two names might be noted here.
	//
	// For a corporate account, the corporate name is used for this attribute.
	// Even if supported by the ASPSP, the provision of this field might depend on the fact whether an explicit consent to this specific additional account information has been given by the PSU.
	OwnerName *OwnerName `json:"ownerName,omitempty"`

	// Product Product Name of the Bank for this account, proprietary definition.
	Product *string `json:"product,omitempty"`

	// ResourceId Id of te account
	ResourceId string `json:"resourceId"`
}

// XS2ABerlinAccountCashAccountType CreditAccount relates to a Credit Account type. Account Type. CurrentAccount relates to a Current Account.
type XS2ABerlinAccountCashAccountType string

// XS2ABerlinAccountDetail defines model for XS2A_Berlin_AccountDetail.
type XS2ABerlinAccountDetail struct {
	Account *XS2ABerlinAccount `json:"account,omitempty"`
}

// XS2ABerlinAccountIdentification Identifies an account through a number or an IBAN.
type XS2ABerlinAccountIdentification struct {
	// AccountNumber Account number.
	AccountNumber *string `json:"accountNumber,omitempty"`

	// Iban Account IBAN.
	Iban *string `json:"iban,omitempty"`
}

// XS2ABerlinAccountsList List of accounts
type XS2ABerlinAccountsList struct {
	// Accounts List of eligible accounts
	Accounts []XS2ABerlinAccount `json:"accounts"`
}

// XS2ABerlinAmount Amount of the transaction in the Account's currency.
type XS2ABerlinAmount struct {
	// Amount Amount for the Balance Type
	Amount string `json:"amount"`

	// Currency Balance Currency
	Currency string `json:"currency"`
}

// XS2ABerlinBalance defines model for XS2A_Berlin_Balance.
type XS2ABerlinBalance struct {
	// BalanceAmount Amount of the transaction in the Account's currency.
	BalanceAmount *XS2ABerlinAmount             `json:"balanceAmount,omitempty"`
	BalanceType   *XS2ABerlinBalanceBalanceType `json:"balanceType,omitempty"`

	// CreditLimitIncluded A flag indicating if the credit limit of the corresponding account is included in the calculation of the balance, where applicable.
	CreditLimitIncluded *bool `json:"creditLimitIncluded,omitempty"`

	// ReferenceDate Date for the Balance Type
	ReferenceDate *string `json:"referenceDate,omitempty"`
}

// XS2ABerlinBalanceBalanceType defines model for XS2ABerlinBalance.BalanceType.
type XS2ABerlinBalanceBalanceType string

// XS2ABerlinBalanceResponse Response for the new balances
type XS2ABerlinBalanceResponse struct {
	Account *struct {
		// Iban Account IBAN.
		Iban *string `json:"iban,omitempty"`
	} `json:"account,omitempty"`

	// Balances Optional. Fetched list of balances only if the withBalance is requested in the query parameters and the consent has been granted.
	Balances *[]XS2ABerlinBalance `json:"balances,omitempty"`
}

// XS2ABerlinCurrencyCode ISO 4217 Alpha 3 currency code
type XS2ABerlinCurrencyCode struct {
	CurrencyCode *string `json:"CurrencyCode,omitempty"`
}

// XS2ABerlinError defines model for XS2A_Berlin_Error.
type XS2ABerlinError struct {
	// ErrorCode Optional error code for reporting purposes.
	ErrorCode *string `json:"errorCode,omitempty"`

	// ErrorDescription The description of the error.
	ErrorDescription *string `json:"errorDescription,omitempty"`
}

// XS2ABerlinExchangeRate Exchange rate
type XS2ABerlinExchangeRate struct {
	ContractIdentification *string            `json:"contractIdentification,omitempty"`
	ExchangeRate           string             `json:"exchangeRate"`
	QuotationDate          openapi_types.Date `json:"quotationDate"`

	// SourceCurrency ISO 4217 Alpha 3 currency code
	SourceCurrency XS2ABerlinCurrencyCode `json:"sourceCurrency"`

	// TargetCurrency ISO 4217 Alpha 3 currency code
	TargetCurrency XS2ABerlinCurrencyCode `json:"targetCurrency"`
	UnitCurrency   string                 `json:"unitCurrency"`
}

// XS2ABerlinLink link to be added
type XS2ABerlinLink struct {
	// CurrentPage Link to a resource
	CurrentPage *HrefType `json:"currentPage,omitempty"`

	// FirstPage Link to a resource
	FirstPage *HrefType `json:"firstPage,omitempty"`

	// LastPage Link to a resource
	LastPage *HrefType `json:"lastPage,omitempty"`

	// NextPage Link to a resource
	NextPage *HrefType `json:"nextPage,omitempty"`

	// SecondPage Link to a resource
	SecondPage *HrefType `json:"secondPage,omitempty"`

	// ViewAccount Link to a resource
	ViewAccount *HrefType `json:"viewAccount,omitempty"`
}

// XS2ABerlinTransaction defines model for XS2A_Berlin_Transaction.
type XS2ABerlinTransaction struct {
	BankTransactionCode *string `json:"bankTransactionCode,omitempty"`

	// BookingDate Date the transaction was created.
	BookingDate *openapi_types.Date `json:"bookingDate,omitempty"`

	// CreditorAccount Identifies an account through a number or an IBAN.
	CreditorAccount *XS2ABerlinAccountIdentification `json:"creditorAccount,omitempty"`

	// CreditorName Name of the creditor if a Debited transaction
	CreditorName *string `json:"creditorName,omitempty"`

	// DebtorAccount Identifies an account through a number or an IBAN.
	DebtorAccount *XS2ABerlinAccountIdentification `json:"debtorAccount,omitempty"`

	// DebtorName Name of the debtor if a Credited transaction
	DebtorName *string `json:"debtorName,omitempty"`

	// EndToEndId Unique reference from the initiating party to beneficiary party.
	EndToEndId   *string                   `json:"endToEndId,omitempty"`
	ExchangeRate *[]XS2ABerlinExchangeRate `json:"exchangeRate,omitempty"`

	// MandateId Identification of Mandates, e.g. a SEPA Mandate ID.
	MandateId   *string `json:"mandateId,omitempty"`
	PurposeCode *string `json:"purposeCode,omitempty"`

	// RemittanceInformationStructured Other information.
	RemittanceInformationStructured *string `json:"remittanceInformationStructured,omitempty"`

	// RemittanceInformationUnstructured The description of the transaction.
	RemittanceInformationUnstructured *string `json:"remittanceInformationUnstructured,omitempty"`

	// TransactionAmount Amount of the transaction in the Account's currency.
	TransactionAmount XS2ABerlinAmount `json:"transactionAmount"`

	// TransactionId Unique Identifier of the transaction.
	TransactionId    *string `json:"transactionId,omitempty"`
	UltimateCreditor *string `json:"ultimateCreditor,omitempty"`
	UltimateDebtor   *string `json:"ultimateDebtor,omitempty"`

	// ValueDate Date the transaction was created.
	ValueDate *openapi_types.Date `json:"valueDate,omitempty"`
}

// XS2ABerlinTransactionList List of transactions
type XS2ABerlinTransactionList = []XS2ABerlinTransaction

// XS2ABerlinTransactionsListAll List of transactions
type XS2ABerlinTransactionsListAll struct {
	// UnderscoreLinks link to be added
	UnderscoreLinks *XS2ABerlinLink `json:"_links,omitempty"`

	// Booked List of transactions
	Booked *XS2ABerlinTransactionList `json:"booked,omitempty"`

	// Pending List of transactions
	Pending *XS2ABerlinTransactionList `json:"pending,omitempty"`
}

// XS2ABerlinTransactionsListResponse List of Transactions and associated links
type XS2ABerlinTransactionsListResponse struct {
	// Transactions List of transactions
	Transactions *XS2ABerlinTransactionsListAll `json:"transactions,omitempty"`
}

// HrefEntry Link to a resource
type HrefEntry = string

// HrefType Link to a resource
type HrefType struct {
	// Href Link to a resource
	Href *HrefEntry `json:"href,omitempty"`
}

// OwnerName Name of the legal account owner.
// If there is more than one owner, then e.g. two names might be noted here.
//
// For a corporate account, the corporate name is used for this attribute.
// Even if supported by the ASPSP, the provision of this field might depend on the fact whether an explicit consent to this specific additional account information has been given by the PSU.
type OwnerName = string

// AccountId defines model for accountId.
type AccountId = string

// BookingStatus defines model for bookingStatus.
type BookingStatus string

// ConsentId defines model for consent-id.
type ConsentId = string

// DateFrom defines model for dateFrom.
type DateFrom = openapi_types.Date

// DateTo defines model for dateTo.
type DateTo = openapi_types.Date

// DeltaList defines model for deltaList.
type DeltaList = bool

// Digest defines model for digest.
type Digest = string

// EntryReferenceFrom defines model for entryReferenceFrom.
type EntryReferenceFrom = string

// Page defines model for page.
type Page = string

// PsuAccept defines model for psu-accept.
type PsuAccept = string

// PsuAcceptCharset defines model for psu-accept-charset.
type PsuAcceptCharset = string

// PsuAcceptEncoding defines model for psu-accept-encoding.
type PsuAcceptEncoding = string

// PsuAcceptLanguage defines model for psu-accept-language.
type PsuAcceptLanguage = string

// PsuDeviceId defines model for psu-device-id.
type PsuDeviceId = openapi_types.UUID

// PsuGeoLocation defines model for psu-geo-location.
type PsuGeoLocation = string

// PsuHttpMethod defines model for psu-http-method.
type PsuHttpMethod string

// PsuIpAddress defines model for psu-ip-address.
type PsuIpAddress = string

// PsuIpPort defines model for psu-ip-port.
type PsuIpPort = string

// PsuUserAgent defines model for psu-user-agent.
type PsuUserAgent = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// WithBalance defines model for withBalance.
type WithBalance = string

// XRequestId defines model for x-request-id.
type XRequestId = openapi_types.UUID

// oAuth2ContextKey is the context key for OAuth2 security scheme
type oAuth2ContextKey string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// GetAccountListParams defines parameters for GetAccountList.
type GetAccountListParams struct {
	// WithBalance If contained, this function reads the list of accessible payment accounts including the booking balance,
	// if granted by the PSU in the related consent and available by the ASPSP.
	// This parameter might be ignored by the ASPSP.
	WithBalance *WithBalance `form:"withBalance,omitempty" json:"withBalance,omitempty"`

	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID XRequestId `json:"X-Request-ID"`

	// ConsentID This then contains the consentId of the related AIS consent, which was performed prior to this payment initiation.
	ConsentID ConsentId `json:"Consent-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *PsuIpAddress `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *PsuIpPort `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *PsuAccept `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *PsuAcceptCharset `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *PsuAcceptEncoding `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *PsuAcceptLanguage `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *PsuUserAgent `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetAccountListParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *PsuDeviceId `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *PsuGeoLocation `json:"PSU-Geo-Location,omitempty"`
}

// GetAccountListParamsPSUHttpMethod defines parameters for GetAccountList.
type GetAccountListParamsPSUHttpMethod string

// GetAccountDetailsParams defines parameters for GetAccountDetails.
type GetAccountDetailsParams struct {
	// WithBalance If contained, this function reads the list of accessible payment accounts including the booking balance,
	// if granted by the PSU in the related consent and available by the ASPSP.
	// This parameter might be ignored by the ASPSP.
	WithBalance *WithBalance `form:"withBalance,omitempty" json:"withBalance,omitempty"`

	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID XRequestId `json:"X-Request-ID"`

	// ConsentID This then contains the consentId of the related AIS consent, which was performed prior to this payment initiation.
	ConsentID ConsentId `json:"Consent-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *PsuIpAddress `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *PsuIpPort `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *PsuAccept `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *PsuAcceptCharset `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *PsuAcceptEncoding `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *PsuAcceptLanguage `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *PsuUserAgent `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetAccountDetailsParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *PsuDeviceId `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *PsuGeoLocation `json:"PSU-Geo-Location,omitempty"`
}

// GetAccountDetailsParamsPSUHttpMethod defines parameters for GetAccountDetails.
type GetAccountDetailsParamsPSUHttpMethod string

// GetBalancesParams defines parameters for GetBalances.
type GetBalancesParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID XRequestId `json:"X-Request-ID"`

	// ConsentID This then contains the consentId of the related AIS consent, which was performed prior to this payment initiation.
	ConsentID ConsentId `json:"Consent-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *PsuIpAddress `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *PsuIpPort `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *PsuAccept `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *PsuAcceptCharset `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *PsuAcceptEncoding `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *PsuAcceptLanguage `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *PsuUserAgent `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetBalancesParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *PsuDeviceId `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *PsuGeoLocation `json:"PSU-Geo-Location,omitempty"`
}

// GetBalancesParamsPSUHttpMethod defines parameters for GetBalances.
type GetBalancesParamsPSUHttpMethod string

// GetTransactionListParams defines parameters for GetTransactionList.
type GetTransactionListParams struct {
	// BookingStatus Permitted codes are
	//   * "booked",
	//   * "pending" and
	//   * "both"
	// "booked" shall be supported by the ASPSP.
	// To support the "pending" and "both" feature is optional for the ASPSP,
	// Error code if not supported in the online banking frontend
	BookingStatus GetTransactionListParamsBookingStatus `form:"bookingStatus" json:"bookingStatus"`

	// DateFrom Conditional: Starting date (inclusive the date dateFrom) of the transaction list, mandated if no delta access is required.
	//
	// For booked transactions, the relevant date is the booking date.
	//
	// For pending transactions, the relevant date is the entry date, which may not be transparent
	// neither in this API nor other channels of the ASPSP.
	DateFrom *DateFrom `form:"dateFrom,omitempty" json:"dateFrom,omitempty"`

	// DateTo End date (inclusive the data dateTo) of the transaction list, default is "now" if not given.
	//
	// Might be ignored if a delta function is used.
	//
	// For booked transactions, the relevant date is the booking date.
	//
	// For pending transactions, the relevant date is the entry date, which may not be transparent
	// neither in this API nor other channels of the ASPSP.
	DateTo *DateTo `form:"dateTo,omitempty" json:"dateTo,omitempty"`

	// EntryReferenceFrom This data attribute is indicating that the AISP is in favour to get all transactions after
	// the transaction with identification entryReferenceFrom alternatively to the above defined period.
	// This is a implementation of a delta access.
	// If this data element is contained, the entries "dateFrom" and "dateTo" might be ignored by the ASPSP
	// if a delta report is supported.
	//
	// Optional if supported by API provider.
	EntryReferenceFrom *EntryReferenceFrom `form:"entryReferenceFrom,omitempty" json:"entryReferenceFrom,omitempty"`

	// DeltaList This data attribute is indicating that the AISP is in favour to get all transactions after the last report access for this PSU on the addressed account. This is another implementation of a delta access-report.
	// This delta indicator might be rejected by the ASPSP if this function is not supported.
	// Optional if supported by API provider
	DeltaList *DeltaList `form:"deltaList,omitempty" json:"deltaList,omitempty"`

	// WithBalance If contained, this function reads the list of accessible payment accounts including the booking balance,
	// if granted by the PSU in the related consent and available by the ASPSP.
	// This parameter might be ignored by the ASPSP.
	WithBalance *WithBalance `form:"withBalance,omitempty" json:"withBalance,omitempty"`

	// Page Current page of the list of transactions.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID XRequestId `json:"X-Request-ID"`

	// ConsentID This then contains the consentId of the related AIS consent, which was performed prior to this payment initiation.
	ConsentID ConsentId `json:"Consent-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *PsuIpAddress `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *PsuIpPort `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *PsuAccept `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *PsuAcceptCharset `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *PsuAcceptEncoding `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *PsuAcceptLanguage `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *PsuUserAgent `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetTransactionListParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *PsuDeviceId `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *PsuGeoLocation `json:"PSU-Geo-Location,omitempty"`
}

// GetTransactionListParamsBookingStatus defines parameters for GetTransactionList.
type GetTransactionListParamsBookingStatus string

// GetTransactionListParamsPSUHttpMethod defines parameters for GetTransactionList.
type GetTransactionListParamsPSUHttpMethod string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccountList request
	GetAccountList(ctx context.Context, params *GetAccountListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccountDetails request
	GetAccountDetails(ctx context.Context, accountId AccountId, params *GetAccountDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBalances request
	GetBalances(ctx context.Context, accountId AccountId, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransactionList request
	GetTransactionList(ctx context.Context, accountId AccountId, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccountList(ctx context.Context, params *GetAccountListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAccountDetails(ctx context.Context, accountId AccountId, params *GetAccountDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountDetailsRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBalances(ctx context.Context, accountId AccountId, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBalancesRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransactionList(ctx context.Context, accountId AccountId, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransactionListRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccountListRequest generates requests for GetAccountList
func NewGetAccountListRequest(server string, params *GetAccountListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.WithBalance != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "withBalance", *params.WithBalance, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Consent-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

		if params.PSUIPAddress != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam5)
		}

		if params.PSUIPPort != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam6)
		}

		if params.PSUAccept != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam7)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam8)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam9)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam10)
		}

		if params.PSUUserAgent != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam11)
		}

		if params.PSUHttpMethod != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam12)
		}

		if params.PSUDeviceID != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam13)
		}

		if params.PSUGeoLocation != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam14)
		}

	}

	return req, nil
}

// NewGetAccountDetailsRequest generates requests for GetAccountDetails
func NewGetAccountDetailsRequest(server string, accountId AccountId, params *GetAccountDetailsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "accountId", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.WithBalance != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "withBalance", *params.WithBalance, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Consent-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

		if params.PSUIPAddress != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam5)
		}

		if params.PSUIPPort != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam6)
		}

		if params.PSUAccept != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam7)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam8)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam9)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam10)
		}

		if params.PSUUserAgent != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam11)
		}

		if params.PSUHttpMethod != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam12)
		}

		if params.PSUDeviceID != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam13)
		}

		if params.PSUGeoLocation != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam14)
		}

	}

	return req, nil
}

// NewGetBalancesRequest generates requests for GetBalances
func NewGetBalancesRequest(server string, accountId AccountId, params *GetBalancesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "accountId", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/balances", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Consent-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

		if params.PSUIPAddress != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam5)
		}

		if params.PSUIPPort != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam6)
		}

		if params.PSUAccept != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam7)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam8)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam9)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam10)
		}

		if params.PSUUserAgent != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam11)
		}

		if params.PSUHttpMethod != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam12)
		}

		if params.PSUDeviceID != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam13)
		}

		if params.PSUGeoLocation != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam14)
		}

	}

	return req, nil
}

// NewGetTransactionListRequest generates requests for GetTransactionList
func NewGetTransactionListRequest(server string, accountId AccountId, params *GetTransactionListParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "accountId", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/accounts/%s/transactions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "bookingStatus", params.BookingStatus, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dateFrom", *params.DateFrom, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dateTo", *params.DateTo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.EntryReferenceFrom != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "entryReferenceFrom", *params.EntryReferenceFrom, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.DeltaList != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "deltaList", *params.DeltaList, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.WithBalance != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "withBalance", *params.WithBalance, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Consent-ID", params.ConsentID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Consent-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

		if params.PSUIPAddress != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam5)
		}

		if params.PSUIPPort != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam6)
		}

		if params.PSUAccept != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam7)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam8)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam9)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam10)
		}

		if params.PSUUserAgent != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam11)
		}

		if params.PSUHttpMethod != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam12)
		}

		if params.PSUDeviceID != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam13)
		}

		if params.PSUGeoLocation != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam14)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccountListWithResponse request
	GetAccountListWithResponse(ctx context.Context, params *GetAccountListParams, reqEditors ...RequestEditorFn) (*GetAccountListResponse, error)

	// GetAccountDetailsWithResponse request
	GetAccountDetailsWithResponse(ctx context.Context, accountId AccountId, params *GetAccountDetailsParams, reqEditors ...RequestEditorFn) (*GetAccountDetailsResponse, error)

	// GetBalancesWithResponse request
	GetBalancesWithResponse(ctx context.Context, accountId AccountId, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*GetBalancesResponse, error)

	// GetTransactionListWithResponse request
	GetTransactionListWithResponse(ctx context.Context, accountId AccountId, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error)
}

type GetAccountListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinAccountsList
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetAccountListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinAccountDetail
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetAccountDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountDetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBalancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinBalanceResponse
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetBalancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBalancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBalancesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTransactionListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *XS2ABerlinTransactionsListResponse
	JSON400      *XS2ABerlinError
	JSON404      *XS2ABerlinError
	JSON408      *XS2ABerlinError
	JSON500      *XS2ABerlinError
}

// Status returns HTTPResponse.Status
func (r GetTransactionListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransactionListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTransactionListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAccountListWithResponse request returning *GetAccountListResponse
func (c *ClientWithResponses) GetAccountListWithResponse(ctx context.Context, params *GetAccountListParams, reqEditors ...RequestEditorFn) (*GetAccountListResponse, error) {
	rsp, err := c.GetAccountList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountListResponse(rsp)
}

// GetAccountDetailsWithResponse request returning *GetAccountDetailsResponse
func (c *ClientWithResponses) GetAccountDetailsWithResponse(ctx context.Context, accountId AccountId, params *GetAccountDetailsParams, reqEditors ...RequestEditorFn) (*GetAccountDetailsResponse, error) {
	rsp, err := c.GetAccountDetails(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountDetailsResponse(rsp)
}

// GetBalancesWithResponse request returning *GetBalancesResponse
func (c *ClientWithResponses) GetBalancesWithResponse(ctx context.Context, accountId AccountId, params *GetBalancesParams, reqEditors ...RequestEditorFn) (*GetBalancesResponse, error) {
	rsp, err := c.GetBalances(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBalancesResponse(rsp)
}

// GetTransactionListWithResponse request returning *GetTransactionListResponse
func (c *ClientWithResponses) GetTransactionListWithResponse(ctx context.Context, accountId AccountId, params *GetTransactionListParams, reqEditors ...RequestEditorFn) (*GetTransactionListResponse, error) {
	rsp, err := c.GetTransactionList(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransactionListResponse(rsp)
}

// ParseGetAccountListResponse parses an HTTP response from a GetAccountListWithResponse call
func ParseGetAccountListResponse(rsp *http.Response) (*GetAccountListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinAccountsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAccountDetailsResponse parses an HTTP response from a GetAccountDetailsWithResponse call
func ParseGetAccountDetailsResponse(rsp *http.Response) (*GetAccountDetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinAccountDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetBalancesResponse parses an HTTP response from a GetBalancesWithResponse call
func ParseGetBalancesResponse(rsp *http.Response) (*GetBalancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBalancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinBalanceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTransactionListResponse parses an HTTP response from a GetTransactionListWithResponse call
func ParseGetTransactionListResponse(rsp *http.Response) (*GetTransactionListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransactionListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest XS2ABerlinTransactionsListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
