// Package consentauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package consentauth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// Defines values for ScaStatus.
const (
	Exempted          ScaStatus = "exempted"
	Failed            ScaStatus = "failed"
	Finalised         ScaStatus = "finalised"
	PsuAuthenticated  ScaStatus = "psuAuthenticated"
	PsuIdentified     ScaStatus = "psuIdentified"
	Received          ScaStatus = "received"
	ScaMethodSelected ScaStatus = "scaMethodSelected"
	Started           ScaStatus = "started"
)

// Valid indicates whether the value is a known member of the ScaStatus enum.
func (e ScaStatus) Valid() bool {
	switch e {
	case Exempted:
		return true
	case Failed:
		return true
	case Finalised:
		return true
	case PsuAuthenticated:
		return true
	case PsuIdentified:
		return true
	case Received:
		return true
	case ScaMethodSelected:
		return true
	case Started:
		return true
	default:
		return false
	}
}

// Defines values for GetConsentAuthorisationParamsPSUHttpMethod.
const (
	GetConsentAuthorisationParamsPSUHttpMethodDELETE GetConsentAuthorisationParamsPSUHttpMethod = "DELETE"
	GetConsentAuthorisationParamsPSUHttpMethodGET    GetConsentAuthorisationParamsPSUHttpMethod = "GET"
	GetConsentAuthorisationParamsPSUHttpMethodPATCH  GetConsentAuthorisationParamsPSUHttpMethod = "PATCH"
	GetConsentAuthorisationParamsPSUHttpMethodPOST   GetConsentAuthorisationParamsPSUHttpMethod = "POST"
	GetConsentAuthorisationParamsPSUHttpMethodPUT    GetConsentAuthorisationParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetConsentAuthorisationParamsPSUHttpMethod enum.
func (e GetConsentAuthorisationParamsPSUHttpMethod) Valid() bool {
	switch e {
	case GetConsentAuthorisationParamsPSUHttpMethodDELETE:
		return true
	case GetConsentAuthorisationParamsPSUHttpMethodGET:
		return true
	case GetConsentAuthorisationParamsPSUHttpMethodPATCH:
		return true
	case GetConsentAuthorisationParamsPSUHttpMethodPOST:
		return true
	case GetConsentAuthorisationParamsPSUHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for StartConsentAuthorisationParamsTPPRedirectPreferred.
const (
	False StartConsentAuthorisationParamsTPPRedirectPreferred = "false"
	True  StartConsentAuthorisationParamsTPPRedirectPreferred = "true"
)

// Valid indicates whether the value is a known member of the StartConsentAuthorisationParamsTPPRedirectPreferred enum.
func (e StartConsentAuthorisationParamsTPPRedirectPreferred) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for StartConsentAuthorisationParamsPSUHttpMethod.
const (
	StartConsentAuthorisationParamsPSUHttpMethodDELETE StartConsentAuthorisationParamsPSUHttpMethod = "DELETE"
	StartConsentAuthorisationParamsPSUHttpMethodGET    StartConsentAuthorisationParamsPSUHttpMethod = "GET"
	StartConsentAuthorisationParamsPSUHttpMethodPATCH  StartConsentAuthorisationParamsPSUHttpMethod = "PATCH"
	StartConsentAuthorisationParamsPSUHttpMethodPOST   StartConsentAuthorisationParamsPSUHttpMethod = "POST"
	StartConsentAuthorisationParamsPSUHttpMethodPUT    StartConsentAuthorisationParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the StartConsentAuthorisationParamsPSUHttpMethod enum.
func (e StartConsentAuthorisationParamsPSUHttpMethod) Valid() bool {
	switch e {
	case StartConsentAuthorisationParamsPSUHttpMethodDELETE:
		return true
	case StartConsentAuthorisationParamsPSUHttpMethodGET:
		return true
	case StartConsentAuthorisationParamsPSUHttpMethodPATCH:
		return true
	case StartConsentAuthorisationParamsPSUHttpMethodPOST:
		return true
	case StartConsentAuthorisationParamsPSUHttpMethodPUT:
		return true
	default:
		return false
	}
}

// Defines values for GetConsentScaStatusParamsPSUHttpMethod.
const (
	DELETE GetConsentScaStatusParamsPSUHttpMethod = "DELETE"
	GET    GetConsentScaStatusParamsPSUHttpMethod = "GET"
	PATCH  GetConsentScaStatusParamsPSUHttpMethod = "PATCH"
	POST   GetConsentScaStatusParamsPSUHttpMethod = "POST"
	PUT    GetConsentScaStatusParamsPSUHttpMethod = "PUT"
)

// Valid indicates whether the value is a known member of the GetConsentScaStatusParamsPSUHttpMethod enum.
func (e GetConsentScaStatusParamsPSUHttpMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// XS2ABerlinError defines model for XS2A_Berlin_Error.
type XS2ABerlinError struct {
	// ErrorCode Optional error code for reporting purposes.
	ErrorCode *string `json:"errorCode,omitempty"`

	// ErrorDescription The description of the error.
	ErrorDescription *string `json:"errorDescription,omitempty"`
}

// Authorisations An array of all authorisationIds
type Authorisations struct {
	// AuthorisationIds An array of all authorisationIds
	AuthorisationIds []string `json:"authorisationIds"`
}

// ScaStatus This data element is containing information about the status of the SCA method applied.
//
// The following codes are defined for this data type.
//
//   - 'received':
//     An authorisation or cancellation-authorisation resource has been created successfully.
//   - 'psuIdentified':
//     The PSU related to the authorisation or cancellation-authorisation resource has been identified.
//   - 'psuAuthenticated':
//     The PSU related to the authorisation or cancellation-authorisation resource has been identified and authenticated e.g. by a password or by an access token.
//   - 'scaMethodSelected':
//     The PSU/TPP has selected the related SCA routine.
//     If the SCA method is chosen implicitly since only one SCA method is available,
//     then this is the first status to be reported instead of 'received'.
//   - 'started':
//     The addressed SCA routine has been started.
//   - 'finalised':
//     The SCA routine has been finalised successfully.
//   - 'failed':
//     The SCA routine failed
//   - 'exempted':
//     SCA was exempted for the related transaction, the related authorisation is successful.
type ScaStatus string

// ScaStatusResponse Body of the JSON response with SCA Status
type ScaStatusResponse struct {
	// ScaStatus This data element is containing information about the status of the SCA method applied.
	//
	// The following codes are defined for this data type.
	//
	//   * 'received':
	//     An authorisation or cancellation-authorisation resource has been created successfully.
	//   * 'psuIdentified':
	//     The PSU related to the authorisation or cancellation-authorisation resource has been identified.
	//   * 'psuAuthenticated':
	//     The PSU related to the authorisation or cancellation-authorisation resource has been identified and authenticated e.g. by a password or by an access token.
	//   * 'scaMethodSelected':
	//     The PSU/TPP has selected the related SCA routine.
	//     If the SCA method is chosen implicitly since only one SCA method is available,
	//     then this is the first status to be reported instead of 'received'.
	//   * 'started':
	//     The addressed SCA routine has been started.
	//   * 'finalised':
	//     The SCA routine has been finalised successfully.
	//   * 'failed':
	//     The SCA routine failed
	//   * 'exempted':
	//     SCA was exempted for the related transaction, the related authorisation is successful.
	ScaStatus *ScaStatus `json:"scaStatus,omitempty"`
}

// StartScaprocessResponse Body of the JSON response for a Start SCA authorisation request.
type StartScaprocessResponse = map[string]interface{}

// Digest defines model for digest.
type Digest = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// GetConsentAuthorisationParams defines parameters for GetConsentAuthorisation.
type GetConsentAuthorisationParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID openapi_types.UUID `json:"X-Request-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *string `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *string `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *string `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *string `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *string `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *string `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *string `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetConsentAuthorisationParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *openapi_types.UUID `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *string `json:"PSU-Geo-Location,omitempty"`
}

// GetConsentAuthorisationParamsPSUHttpMethod defines parameters for GetConsentAuthorisation.
type GetConsentAuthorisationParamsPSUHttpMethod string

// StartConsentAuthorisationJSONBody defines parameters for StartConsentAuthorisation.
type StartConsentAuthorisationJSONBody = map[string]interface{}

// StartConsentAuthorisationParams defines parameters for StartConsentAuthorisation.
type StartConsentAuthorisationParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID openapi_types.UUID `json:"X-Request-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUID Client ID of the PSU in the ASPSP client interface. It is mandated by the Raiffeisen Bank to be required field if the PSU-Corporate-ID is not provided. It might be contained even if an OAuth2 based authentication was performed in a pre-step In this case the ASPSP might check whether PSU-ID and token match, according to ASPSP documentation.
	PSUID *string `json:"PSU-ID,omitempty"`

	// PSUIDType Type of the PSU-ID, needed in scenarios where PSUs have several PSU-IDs as access possibility.
	PSUIDType *string `json:"PSU-ID-Type,omitempty"`

	// PSUCorporateID It is mandated by the Raiffeisen Bank to be required field if the PSU-ID is not provided.
	PSUCorporateID *string `json:"PSU-Corporate-ID,omitempty"`

	// PSUCorporateIDType Might be mandated in the ASPSP's documentation. Only used in a corporate context.
	PSUCorporateIDType *string `json:"PSU-Corporate-ID-Type,omitempty"`

	// TPPRedirectPreferred If it equals "true", the TPP prefers a redirect over an embedded SCA approach.
	// If it equals "false", the TPP prefers not to be redirected for SCA. The ASPSP will then choose between the Embedded or the Decoupled
	// SCA approach, depending on the choice of the SCA procedure by the TPP/PSU.
	// If the parameter is not used, the ASPSP will choose the SCA approach to be applied depending on the SCA method chosen by the
	// TPP/PSU.
	TPPRedirectPreferred *StartConsentAuthorisationParamsTPPRedirectPreferred `json:"TPP-Redirect-Preferred,omitempty"`

	// TPPRedirectURI URI of the URI of the TPP, where the transaction flow shall be redirected to after a Redirect. Mandated for the Redirect SCA Approach, specifically when TPP-Redirect- Preferred equals "true". See Section 4.10 for further requirements on this header. It is recommended to always use this header field.
	TPPRedirectURI *string `json:"TPP-Redirect-URI,omitempty"`

	// TPPNokRedirectURI If this URI is contained, the TPP is asking to redirect the transaction flow to this address instead of the TPP-Redirect-URI in case
	// of a negative result of the redirect SCA method. This might be ignored by the ASPSP.
	TPPNokRedirectURI *string `json:"TPP-Nok-Redirect-URI,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *string `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *string `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *string `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *string `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *string `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *string `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *string `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *StartConsentAuthorisationParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *openapi_types.UUID `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *string `json:"PSU-Geo-Location,omitempty"`
}

// StartConsentAuthorisationParamsTPPRedirectPreferred defines parameters for StartConsentAuthorisation.
type StartConsentAuthorisationParamsTPPRedirectPreferred string

// StartConsentAuthorisationParamsPSUHttpMethod defines parameters for StartConsentAuthorisation.
type StartConsentAuthorisationParamsPSUHttpMethod string

// GetConsentScaStatusParams defines parameters for GetConsentScaStatus.
type GetConsentScaStatusParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID openapi_types.UUID `json:"X-Request-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`

	// PSUIPAddress The forwarded IP Address header field consists of the corresponding HTTP request
	// IP Address field between PSU and TPP.
	// It shall be contained if and only if this request was actively initiated by the PSU.
	PSUIPAddress *string `json:"PSU-IP-Address,omitempty"`

	// PSUIPPort The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
	PSUIPPort *string `json:"PSU-IP-Port,omitempty"`

	// PSUAccept The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAccept *string `json:"PSU-Accept,omitempty"`

	// PSUAcceptCharset The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptCharset *string `json:"PSU-Accept-Charset,omitempty"`

	// PSUAcceptEncoding The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptEncoding *string `json:"PSU-Accept-Encoding,omitempty"`

	// PSUAcceptLanguage The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP, if available.
	PSUAcceptLanguage *string `json:"PSU-Accept-Language,omitempty"`

	// PSUUserAgent The forwarded Agent header field of the HTTP request between
	// PSU and TPP, if available.
	// Examples
	//   * Android:  "Myappa/1.2 Dalvik/2.1.0 (Linux; U; Android 6.0.1; vivo 1610 Build/MMB29M)"
	//   * iOS: "MyApp/1 iPhone5,2 iOS/10_1 CFNetwork/808.3 Darwin/16.3.0"
	PSUUserAgent *string `json:"PSU-User-Agent,omitempty"`

	// PSUHttpMethod HTTP method used at the PSU ? TPP interface, if available.
	// Valid values are:
	// * GET
	// * POST
	// * PUT
	// * PATCH
	// * DELETE
	PSUHttpMethod *GetConsentScaStatusParamsPSUHttpMethod `json:"PSU-Http-Method,omitempty"`

	// PSUDeviceID UUID (Universally Unique Identifier) for a device, which is used by the PSU, if available.
	// UUID identifies either a device or a device dependant application installation.
	// In case of an installation identification this ID need to be unaltered until removal from device.
	PSUDeviceID *openapi_types.UUID `json:"PSU-Device-ID,omitempty"`

	// PSUGeoLocation The forwarded Geo Location of the corresponding http request between PSU and TPP if available.
	PSUGeoLocation *string `json:"PSU-Geo-Location,omitempty"`
}

// GetConsentScaStatusParamsPSUHttpMethod defines parameters for GetConsentScaStatus.
type GetConsentScaStatusParamsPSUHttpMethod string

// StartConsentAuthorisationJSONRequestBody defines body for StartConsentAuthorisation for application/json ContentType.
type StartConsentAuthorisationJSONRequestBody = StartConsentAuthorisationJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetConsentAuthorisation request
	GetConsentAuthorisation(ctx context.Context, consentId string, params *GetConsentAuthorisationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartConsentAuthorisationWithBody request with any body
	StartConsentAuthorisationWithBody(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartConsentAuthorisation(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, body StartConsentAuthorisationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConsentScaStatus request
	GetConsentScaStatus(ctx context.Context, consentId string, authorisationId string, params *GetConsentScaStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetConsentAuthorisation(ctx context.Context, consentId string, params *GetConsentAuthorisationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConsentAuthorisationRequest(c.Server, consentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConsentAuthorisationWithBody(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConsentAuthorisationRequestWithBody(c.Server, consentId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConsentAuthorisation(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, body StartConsentAuthorisationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConsentAuthorisationRequest(c.Server, consentId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConsentScaStatus(ctx context.Context, consentId string, authorisationId string, params *GetConsentScaStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConsentScaStatusRequest(c.Server, consentId, authorisationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetConsentAuthorisationRequest generates requests for GetConsentAuthorisation
func NewGetConsentAuthorisationRequest(server string, consentId string, params *GetConsentAuthorisationParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s/authorisations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		if params.Digest != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam1)
		}

		if params.Signature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam2)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam3)
		}

		if params.PSUIPAddress != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam4)
		}

		if params.PSUIPPort != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam5)
		}

		if params.PSUAccept != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam6)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam7)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam8)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam9)
		}

		if params.PSUUserAgent != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam10)
		}

		if params.PSUHttpMethod != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam11)
		}

		if params.PSUDeviceID != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam12)
		}

		if params.PSUGeoLocation != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam13)
		}

	}

	return req, nil
}

// NewStartConsentAuthorisationRequest calls the generic StartConsentAuthorisation builder with application/json body
func NewStartConsentAuthorisationRequest(server string, consentId string, params *StartConsentAuthorisationParams, body StartConsentAuthorisationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartConsentAuthorisationRequestWithBody(server, consentId, params, "application/json", bodyReader)
}

// NewStartConsentAuthorisationRequestWithBody generates requests for StartConsentAuthorisation with any type of body
func NewStartConsentAuthorisationRequestWithBody(server string, consentId string, params *StartConsentAuthorisationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s/authorisations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		if params.Digest != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam1)
		}

		if params.Signature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam2)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam3)
		}

		if params.PSUID != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID", *params.PSUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID", headerParam4)
		}

		if params.PSUIDType != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID-Type", *params.PSUIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-ID-Type", headerParam5)
		}

		if params.PSUCorporateID != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID", *params.PSUCorporateID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID", headerParam6)
		}

		if params.PSUCorporateIDType != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Corporate-ID-Type", *params.PSUCorporateIDType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Corporate-ID-Type", headerParam7)
		}

		if params.TPPRedirectPreferred != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-Preferred", *params.TPPRedirectPreferred, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-Preferred", headerParam8)
		}

		if params.TPPRedirectURI != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "TPP-Redirect-URI", *params.TPPRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Redirect-URI", headerParam9)
		}

		if params.TPPNokRedirectURI != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "TPP-Nok-Redirect-URI", *params.TPPNokRedirectURI, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Nok-Redirect-URI", headerParam10)
		}

		if params.PSUIPAddress != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam11)
		}

		if params.PSUIPPort != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam12)
		}

		if params.PSUAccept != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam13)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam14 string

			headerParam14, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam14)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam15 string

			headerParam15, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam15)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam16 string

			headerParam16, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam16)
		}

		if params.PSUUserAgent != nil {
			var headerParam17 string

			headerParam17, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam17)
		}

		if params.PSUHttpMethod != nil {
			var headerParam18 string

			headerParam18, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam18)
		}

		if params.PSUDeviceID != nil {
			var headerParam19 string

			headerParam19, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam19)
		}

		if params.PSUGeoLocation != nil {
			var headerParam20 string

			headerParam20, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam20)
		}

	}

	return req, nil
}

// NewGetConsentScaStatusRequest generates requests for GetConsentScaStatus
func NewGetConsentScaStatusRequest(server string, consentId string, authorisationId string, params *GetConsentScaStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "consentId", consentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "authorisationId", authorisationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/consents/%s/authorisations/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		if params.Digest != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam1)
		}

		if params.Signature != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam2)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam3)
		}

		if params.PSUIPAddress != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Address", *params.PSUIPAddress, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Address", headerParam4)
		}

		if params.PSUIPPort != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithOptions("simple", false, "PSU-IP-Port", *params.PSUIPPort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-IP-Port", headerParam5)
		}

		if params.PSUAccept != nil {
			var headerParam6 string

			headerParam6, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept", *params.PSUAccept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept", headerParam6)
		}

		if params.PSUAcceptCharset != nil {
			var headerParam7 string

			headerParam7, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Charset", *params.PSUAcceptCharset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Charset", headerParam7)
		}

		if params.PSUAcceptEncoding != nil {
			var headerParam8 string

			headerParam8, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Encoding", *params.PSUAcceptEncoding, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Encoding", headerParam8)
		}

		if params.PSUAcceptLanguage != nil {
			var headerParam9 string

			headerParam9, err = runtime.StyleParamWithOptions("simple", false, "PSU-Accept-Language", *params.PSUAcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Accept-Language", headerParam9)
		}

		if params.PSUUserAgent != nil {
			var headerParam10 string

			headerParam10, err = runtime.StyleParamWithOptions("simple", false, "PSU-User-Agent", *params.PSUUserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-User-Agent", headerParam10)
		}

		if params.PSUHttpMethod != nil {
			var headerParam11 string

			headerParam11, err = runtime.StyleParamWithOptions("simple", false, "PSU-Http-Method", *params.PSUHttpMethod, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Http-Method", headerParam11)
		}

		if params.PSUDeviceID != nil {
			var headerParam12 string

			headerParam12, err = runtime.StyleParamWithOptions("simple", false, "PSU-Device-ID", *params.PSUDeviceID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Device-ID", headerParam12)
		}

		if params.PSUGeoLocation != nil {
			var headerParam13 string

			headerParam13, err = runtime.StyleParamWithOptions("simple", false, "PSU-Geo-Location", *params.PSUGeoLocation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("PSU-Geo-Location", headerParam13)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetConsentAuthorisationWithResponse request
	GetConsentAuthorisationWithResponse(ctx context.Context, consentId string, params *GetConsentAuthorisationParams, reqEditors ...RequestEditorFn) (*GetConsentAuthorisationResponse, error)

	// StartConsentAuthorisationWithBodyWithResponse request with any body
	StartConsentAuthorisationWithBodyWithResponse(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConsentAuthorisationResponse, error)

	StartConsentAuthorisationWithResponse(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, body StartConsentAuthorisationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConsentAuthorisationResponse, error)

	// GetConsentScaStatusWithResponse request
	GetConsentScaStatusWithResponse(ctx context.Context, consentId string, authorisationId string, params *GetConsentScaStatusParams, reqEditors ...RequestEditorFn) (*GetConsentScaStatusResponse, error)
}

type GetConsentAuthorisationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Authorisations
	JSON400      *XS2ABerlinError
	JSON401      *XS2ABerlinError
	JSON500      *interface{}
	JSON503      *interface{}
}

// Status returns HTTPResponse.Status
func (r GetConsentAuthorisationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConsentAuthorisationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConsentAuthorisationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartConsentAuthorisationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *StartScaprocessResponse
	JSON400      *XS2ABerlinError
	JSON401      *XS2ABerlinError
	JSON500      *interface{}
	JSON503      *interface{}
}

// Status returns HTTPResponse.Status
func (r StartConsentAuthorisationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartConsentAuthorisationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartConsentAuthorisationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConsentScaStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScaStatusResponse
	JSON400      *XS2ABerlinError
	JSON401      *XS2ABerlinError
	JSON500      *interface{}
	JSON503      *interface{}
}

// Status returns HTTPResponse.Status
func (r GetConsentScaStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConsentScaStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConsentScaStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetConsentAuthorisationWithResponse request returning *GetConsentAuthorisationResponse
func (c *ClientWithResponses) GetConsentAuthorisationWithResponse(ctx context.Context, consentId string, params *GetConsentAuthorisationParams, reqEditors ...RequestEditorFn) (*GetConsentAuthorisationResponse, error) {
	rsp, err := c.GetConsentAuthorisation(ctx, consentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConsentAuthorisationResponse(rsp)
}

// StartConsentAuthorisationWithBodyWithResponse request with arbitrary body returning *StartConsentAuthorisationResponse
func (c *ClientWithResponses) StartConsentAuthorisationWithBodyWithResponse(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConsentAuthorisationResponse, error) {
	rsp, err := c.StartConsentAuthorisationWithBody(ctx, consentId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConsentAuthorisationResponse(rsp)
}

func (c *ClientWithResponses) StartConsentAuthorisationWithResponse(ctx context.Context, consentId string, params *StartConsentAuthorisationParams, body StartConsentAuthorisationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConsentAuthorisationResponse, error) {
	rsp, err := c.StartConsentAuthorisation(ctx, consentId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConsentAuthorisationResponse(rsp)
}

// GetConsentScaStatusWithResponse request returning *GetConsentScaStatusResponse
func (c *ClientWithResponses) GetConsentScaStatusWithResponse(ctx context.Context, consentId string, authorisationId string, params *GetConsentScaStatusParams, reqEditors ...RequestEditorFn) (*GetConsentScaStatusResponse, error) {
	rsp, err := c.GetConsentScaStatus(ctx, consentId, authorisationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConsentScaStatusResponse(rsp)
}

// ParseGetConsentAuthorisationResponse parses an HTTP response from a GetConsentAuthorisationWithResponse call
func ParseGetConsentAuthorisationResponse(rsp *http.Response) (*GetConsentAuthorisationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConsentAuthorisationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Authorisations
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseStartConsentAuthorisationResponse parses an HTTP response from a StartConsentAuthorisationWithResponse call
func ParseStartConsentAuthorisationResponse(rsp *http.Response) (*StartConsentAuthorisationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartConsentAuthorisationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest StartScaprocessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetConsentScaStatusResponse parses an HTTP response from a GetConsentScaStatusWithResponse call
func ParseGetConsentScaStatusResponse(rsp *http.Response) (*GetConsentScaStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConsentScaStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScaStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest XS2ABerlinError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
