// Package cleanuppayments provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package cleanuppayments

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientIdHeaderScopes clientIdHeaderContextKey = "clientIdHeader.Scopes"
)

// PSUID defines model for PSU-ID.
type PSUID = string

// XRequestID defines model for X-Request-ID.
type XRequestID = openapi_types.UUID

// Digest defines model for digest.
type Digest = string

// Signature defines model for signature.
type Signature = string

// TppSignatureCertificate defines model for tpp-signature-certificate.
type TppSignatureCertificate = string

// clientIdHeaderContextKey is the context key for clientIdHeader security scheme
type clientIdHeaderContextKey string

// PaymentsCleanUpParams defines parameters for PaymentsCleanUp.
type PaymentsCleanUpParams struct {
	// XRequestID ID of the request, unique to the call, as determined by the initiating party.
	XRequestID XRequestID `json:"X-Request-ID"`

	// PSUID Client ID of the PSU in the ASPSP client interface. It is mandated by the Raiffeisen Bank to be required field if the PSU-Corporate-ID is not provided. It might be contained even if an OAuth2 based authentication was performed in a pre-step In this case the ASPSP might check whether PSU-ID and token match, according to ASPSP documentation.
	PSUID PSUID `json:"PSU-ID"`

	// Digest The digest is a base64 encoded hash of the body.
	// Hash the body of your request (or an empty string if there is no body) using the SHA-256 algorithm.
	// Base64 encode the output and add the result to your Digest header, specifying the hashing algorithm used.
	Digest *Digest `json:"Digest,omitempty"`

	// Signature A signature of the request by the TPP at the application level. This might be mandated by the ASPSP.
	// The signature is a list of headers with their signed values. Any header can be used in the signature (including the `Digest` header), with the exception of the `client_id` header.
	// To sign the `client_id` header, its name should be treated as `clientId`.
	// First, prepare the headers in the format of "header name: header value" with a line separator, e.g.,
	// ```
	// Digest: SHA-256=ZuYiOtZkVxhjWmwTO5lOpsPevUNMezvk6dfb6fVhebM=
	// clientId: WmwTO5lOpsPevUNMezvk6df
	// ```
	// Then, sign this string using your private key and hash it with SHA-256 using RSA.
	// Finally, base64 encode the resulting value. The `Signature` header should include the `keyId`, `algorithm="rsa-sha256"`, `headers` list, and the base64 encoded signature.
	Signature *Signature `json:"Signature,omitempty"`

	// TPPSignatureCertificate The certificate used for signing the request, in base64 encoding.
	// Must be included if a signature is present. The request must be signed with your QSEAL certificate.
	// The algorithm used for the signature must be RSA-SHA256. If this header is present, the `Signature` and `Digest` headers must also be provided.
	TPPSignatureCertificate *TppSignatureCertificate `json:"TPP-Signature-Certificate,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PaymentsCleanUp request
	PaymentsCleanUp(ctx context.Context, params *PaymentsCleanUpParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PaymentsCleanUp(ctx context.Context, params *PaymentsCleanUpParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentsCleanUpRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPaymentsCleanUpRequest generates requests for PaymentsCleanUp
func NewPaymentsCleanUpRequest(server string, params *PaymentsCleanUpParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/payments/clean-up")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Request-ID", params.XRequestID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Request-ID", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "PSU-ID", params.PSUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("PSU-ID", headerParam1)

		if params.Digest != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithOptions("simple", false, "Digest", *params.Digest, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Digest", headerParam2)
		}

		if params.Signature != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithOptions("simple", false, "Signature", *params.Signature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Signature", headerParam3)
		}

		if params.TPPSignatureCertificate != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithOptions("simple", false, "TPP-Signature-Certificate", *params.TPPSignatureCertificate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("TPP-Signature-Certificate", headerParam4)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PaymentsCleanUpWithResponse request
	PaymentsCleanUpWithResponse(ctx context.Context, params *PaymentsCleanUpParams, reqEditors ...RequestEditorFn) (*PaymentsCleanUpResponse, error)
}

type PaymentsCleanUpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PaymentsCleanUpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PaymentsCleanUpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PaymentsCleanUpResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PaymentsCleanUpWithResponse request returning *PaymentsCleanUpResponse
func (c *ClientWithResponses) PaymentsCleanUpWithResponse(ctx context.Context, params *PaymentsCleanUpParams, reqEditors ...RequestEditorFn) (*PaymentsCleanUpResponse, error) {
	rsp, err := c.PaymentsCleanUp(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentsCleanUpResponse(rsp)
}

// ParsePaymentsCleanUpResponse parses an HTTP response from a PaymentsCleanUpWithResponse call
func ParsePaymentsCleanUpResponse(rsp *http.Response) (*PaymentsCleanUpResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PaymentsCleanUpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
